test: SQLRestriction에 대한 테스트 추가
GDSC-Hongik/gdsc-server pull request #302
Opened 2024-04-16 07:08 UTC by Sangwook02

## 🌱 관련 이슈
- close #298

## 📌 작업 내용 및 특이사항
- `@SQLRestriction`에 따라 `MemberStatus.NORMAL`인 회원만 조회되어야 하므로 이에 대한 테스트를 작성했습니다.
- 모든 조회 메서드에 대해 테스트를 하는 것은 비효율적이므로 `findAll` 메서드에 대해서만 테스트를 작성했습니다.
- 멤버 상태를 `MemberStatus.FORBIDDEN`으로 바꾸는 도메인 메서드가 없기 때문에 이에 대한 테스트는 작성하지 않았습니다. 향후 메서드가 구현되면 테스트를 작성하면 좋을 것 같습니다.

## 📝 참고사항
-

## 📚 기타
-

2024-04-19 10:32 UTC, uwoobeat requested changes

2024-04-19 10:32 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
> +    class 멤버_상태에_따른_조회 {
class 이름은 ~~할 때로 통일하면 어떨까 싶네요
ex) `멤버_상태로_조회할때` / `XX이면_OO_성공한다()`

2024-04-19 11:17 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
> +    class 멤버_상태에_따른_조회 {
오 좋네요
반영하겠습니다~

2024-04-19 11:31 UTC, AlmondBreez3 approved these changes
확인했습니다!

2024-04-20 06:33 UTC, uwoobeat approved these changes
lgtm

2024-04-20 09:41 UTC, merged