test: 역할에 대한 멤버 레포지토리 테스트 추가
GDSC-Hongik/gdsc-server pull request #314
Opened 2024-04-22 02:17 UTC by Sangwook02

## 🌱 관련 이슈
- close #310 

## 📌 작업 내용 및 특이사항
- MemberRole에 대한 레포지토리 테스트를 작성했습니다.
- 승인 전과 후의 상황에 대해서, GUEST와 USER로 조회하는 상황을 테스트합니다.

## 📝 참고사항
```java
private static final String UNIV_EMAIL = "test@g.hongik.ac.kr";
private static final String DISCORD_USERNAME = "testDiscord";
private static final String NICKNAME = "testNickname";
private static final String NAME = "김홍익";
private static final String STUDENT_ID = "C123456";
private static final String PHONE_NUMBER = "01012345678";
```
- 멤버 토메인 테스트에서도 사용하는 상수들을 레포지토리 테스트에서도 똑같이 사용해야 합니다.
각 테스트에서 상수를 정의하기 보다는 상수 클래스를 활용하는 것이 좋을 것 같아, 
Issue #313 을 열었습니다.
## 📚 기타
-

2024-04-25 03:02 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
> +            member.grant();
'// when'에 있는 조회 쿼리가 나가기전에 update 쿼리가 한 번 더 나가서 변경사항이 모두 반영됩니다!

2024-04-25 12:16 UTC, uwoobeat requested changes

2024-04-25 12:16 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
> +            member.grant();
아 DataJpaTest에 Transactional 붙어있던걸 깜빡했네요
이거 테스트 전체에 `@Transactional` 이 붙는거라 when 절에서 sut 실행하기 전에 `em.flush()` + `em.clear()` 실행해주는게 검증 측면에서 좋을 것 같아요.

2024-04-26 13:10 UTC, uwoobeat requested changes

2024-04-26 13:10 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
> +    private void flushAndClear() {
음 컨텍스트를 조금 더 살려서 `flushAndClearBeforeExecute()` 는 어떨까요

2024-04-26 13:12 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
> +    private void flushAndClear() {
좋아요
근데 이 메서드를 when의 맨 앞에서 호출하는게 맞을지 아니면 given의 마지막에 호출하는게 맞을지 좀 의문이긴해요.
하는 일은 update 쿼리 날리는건데 그럼 given의 마지막에서 호출하는게 적절한 것 같기도 해서요

2024-04-26 13:14 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
> +    private void flushAndClear() {
given절을 마무리하는 느낌이 강한 것 같아서 given절 마지막에 호출하는 게 좋을 것 같아요

2024-04-26 13:14 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
> +    private void flushAndClear() {
그쵸? 의견 감사드려요👍

2024-04-27 06:52 UTC, AlmondBreez3 approved these changes
확인했습니다

2024-04-27 13:57 UTC, uwoobeat approved these changes
lgtm

2024-04-27 14:35 UTC, merged