feat: application 도메인 구현
GDSC-Hongik/gdsc-server pull request #322
Opened 2024-04-29 13:53 UTC by Sangwook02

## 🌱 관련 이슈
- close #319

## 📌 작업 내용 및 특이사항
- application 엔티티, 서비스, 레포지토리를 생성했습니다.
   - 활동 기간을 나타내는 BaseTermEntity를  MappedSuperClass로 만들고 Application이 이를 상속하도록 했습니다.
   - BaseTermEntity의 Semester는 Enum 타입으로 만들어 넣었습니다.
- 테스트가 깨져서 원인을 파악해보니 h2에서 year가 예약이기 때문이었고, `application-test.yml`에서 year를 사용할 수 있도록 설정했습니다.

## 📝 참고사항
-

## 📚 기타
-

2024-04-29 15:12 UTC, AlmondBreez3 approved these changes
수고하셨습니당

2024-04-30 12:08 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/common/model/BaseTermEntity.java
> +    public enum Semester {
enum을 내부 클래스로 선언한 이유가 궁금합니다~

2024-05-01 02:51 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/common/model/BaseTermEntity.java
> +    public enum Semester {
특별한 이유가 있어서라기보다는 일단 BaseTermEntity 만들어두고 분리하려다가 놓쳤습니다!
감사합니다~

2024-05-01 06:41 UTC, uwoobeat requested changes

2024-05-01 06:41 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/common/model/BaseTermEntity.java
> +    @Column
다른 이름으로 매핑할 것이 아니기 때문에, `@Column` 은 생략해도 될 것 같습니다.

2024-05-01 06:59 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/common/model/BaseTermEntity.java
> +    @Column
꼼꼼하게 봐주셔서 감사합니다!
수정했어요~

2024-05-01 09:10 UTC, uwoobeat approved these changes
lgtm

2024-05-01 09:11 UTC, merged