feat: 가입 신청서 생성 API 구현
GDSC-Hongik/gdsc-server pull request #326
Opened 2024-05-03 12:38 UTC by Sangwook02

## 🌱 관련 이슈
- close #325

## 📌 작업 내용 및 특이사항
- 가입 신청서를 생성하는 API를 구현했습니다.
- GUEST인 경우 가입 신청서를 작성하려고 하면 예외가 발생하도록 했습니다.

## 📝 참고사항
-

## 📚 기타
-

2024-05-04 10:27 UTC, uwoobeat requested changes

2024-05-04 10:27 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/application/api/ApplicationController.java
> +    public ResponseEntity<Void> apply() {
가입신청서 생성 대신 '가입신청서 접수' 같은 명료한 워딩을 사용하는 것이 좋아보입니다
컨트롤러, 서비스 메서드 이름도 기존 컨벤션과 달라서 조금 어색한 부분이 있네요.

2024-05-04 10:27 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/application/application/ApplicationService.java
> +    public void apply() {
`@Transactional` 을 추가해야 합니다.

2024-05-04 10:27 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/application/domain/Application.java
> +        if (!member.isGranted()) {
게스트인 유저만 신청서를 접수할 수 있어야 하는 것 아닌가요? 로직이 반대로 된 것 같습니다.

2024-05-04 10:27 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/application/application/ApplicationServiceTest.java
> +        void 역할이_GUEST라면_가입신청서_생성에_실패한다() {
`createApplication` 에서는 이미 승인된 멤버인지를 검증하고 있고, 이 승인된 멤버인지의 여부는 내부적으로 USER, ADMIN 역할인지로 체크하긴 하나 이 구현과는 무관하게 `isGranted` 의 여부로 검증해야 합니다.

즉 `validateMemberGranted` 에 대하여 `isGranted` 가 아닌, `isGranted` 의 내부 구현에 의존하는 테스트를 작성하는 경우 리팩토링 내성에  취약해집니다. 가령 GUEST도 `isGranted` 로 판정하도록 요구사항이 바뀌는 경우가 생긴다면 전혀 상관없는 가입신청 테스트가 깨지게 됩니다.

2024-05-04 11:40 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/application/domain/Application.java
> +        if (!member.isGranted()) {
디스코드, Bevy, 재학생 인증을 마치고 MemberRole이 USER로 변경된 후에 신청서를 접수하게 되는 것이므로 현재의 로직이 맞습니다!

2024-05-04 12:51 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/application/domain/Application.java
> +        if (!member.isGranted()) {
USER는 이번 학기 활동 권한이 있는 멤버를 의미하는 것 아닌가요?
저번에 논의하기로는 GUEST와 USER 사이에 DORMANT를 넣자 이런 이야기도 했었고요.
그리고 어드민에서 grant() 호출하여 USER를 주는 로직이 변경될 예정이라 이쪽 스펙에 대한 이야기도 해봐야 할듯 합니다

2024-05-05 10:27 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/application/domain/Application.java
> +        if (!member.isGranted()) {
지난번 회의에서 MemberRole은 현 상태를 유지하고 Membership으로 유지하자고 정했던 걸로 이해했습니다. 아마 한비님도 그렇게 알고 계실거고요.. 확실히 문서화 작업이 필요하겠네요.
오늘 회의에서 다시 논의해봐요!

2024-05-11 12:21 UTC, AlmondBreez3 approved these changes
어푸르브 해씁니당

2024-05-12 14:07 UTC, uwoobeat requested changes
recruitment 기간 사이에 대한 정책 + 리쿠르팅 기간별 중복 신청에 대한 정책등
정책적으로 더 꼼꼼하게 validation이 이루어져야 할 것 같습니다

2024-05-14 10:09 UTC, AlmondBreez3 approved these changes
lgtm

2024-05-16 05:35 UTC, uwoobeat requested changes

2024-05-16 05:35 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        Recruitment recruitment = recruitmentUtil.getOpenRecruitment();
리쿠르팅에도 조회 유틸리티를 만든 이유가 궁금합니다~

2024-05-16 05:35 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        Membership membership = Membership.createMembership(
지원기간이 아닌 경우 지원이 불가능하도록 검증하는 메서드가 있어야 할듯 합니다.

2024-05-16 05:38 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        Membership membership = Membership.createMembership(
리쿠르팅 유틸리티 클래스의 getOpenRecruitment 메서드에서 처리해줍니다

2024-05-16 05:40 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        Recruitment recruitment = recruitmentUtil.getOpenRecruitment();
열려있는 리쿠르트먼트를 조회하는 메서드는 여러 서비스에서 활용하게 될 것 같아서 유틸리티 클래스로 만들었어요

2024-05-16 10:13 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        Recruitment recruitment = recruitmentUtil.getOpenRecruitment();
가령 어떤 케이스가 있는지 예시를 알 수 있을까요?

2024-05-16 10:15 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        Membership membership = Membership.createMembership(
그렇다면 해당 케이스에 대한 테스트 코드를 서비스 단에서도 작성해주세요~

2024-05-17 03:04 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        Recruitment recruitment = recruitmentUtil.getOpenRecruitment();
리쿠르트먼트를 만들거나 수정할 때도 필요할거라고 생각했는데 다시 생각해보니 그 경우에는 로직이 좀 다르겠네요

서비스로 옮기고 아래에 있는 리뷰에 따라 테스트 추가하겠습니다

2024-05-17 03:08 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        Membership membership = Membership.createMembership(
오 근데 말씀하신 케이스에 대한 테스트가 이미 있네요
어제는 제가 밖에서 리뷰를 확인하느라 제대로 확인을 못 했는데 `MembershipServiceTest.열려있는_Recruitment가_없다면_실패한다`가 `지원기간이 아닌 경우 지원이 불가능하도록 검증하는 메서드`입니다~

2024-05-17 15:01 UTC, uwoobeat requested changes

2024-05-17 15:01 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +    private Recruitment getOpenRecruitment() {
해당 로직을 메서드로 추출하신 이유가 있나요?

2024-05-18 01:48 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +    private Recruitment getOpenRecruitment() {
이걸 위에 있는 public 메서드에 통째로 넣어버리면 너무 길어져서 메서드 로직을 읽기가 어려워지더라구요.
가독성 차원에서 분리했습니다.

2024-05-19 11:02 UTC, uwoobeat requested changes
이거 처음부터 구현이 묘하게 거슬렸었는데, 지금 보니 날짜에 종속적인 기능이라 그런 것 같습니다.

구현에 '오늘'이라는 기준을 넣게 되면 get 요청의 경우 멱등성을 지킬 수 없게 되며, get이 아닌 post의 경우더라도 테스트하기 어려운 코드가 만들어집니다.

실제로 현재 멤버십 서비스 테스트 시 리쿠르팅을 생성할 때 NOW를 자주 사용하고 있는데, 테스트 안티패턴이므로 지양해야 합니다. 이를 위해서는 현재 시점에 종속적인 구현을 만들어서는 안됩니다.

(조회의 경우) 클라이언트가 현재 날짜에 대한 컨텍스트를 전달하게 하고, 이를 바탕으로 학년도-학기를 확정하게 하는 것이 좋을 것 같고요, 멤버십 신청 접수하기의 경우 리쿠르팅 ID를 쿼리 파라미터로 받게 하면 이러한 문제가 해결될 것 같습니다.

2024-05-20 02:58 UTC, Sangwook02 commented
> 이거 처음부터 구현이 묘하게 거슬렸었는데, 지금 보니 날짜에 종속적인 기능이라 그런 것 같습니다.
> 
> 구현에 '오늘'이라는 기준을 넣게 되면 get 요청의 경우 멱등성을 지킬 수 없게 되며, get이 아닌 post의 경우더라도 테스트하기 어려운 코드가 만들어집니다.
> 
> 실제로 현재 멤버십 서비스 테스트 시 리쿠르팅을 생성할 때 NOW를 자주 사용하고 있는데, 테스트 안티패턴이므로 지양해야 합니다. 이를 위해서는 현재 시점에 종속적인 구현을 만들어서는 안됩니다.
> 
> (조회의 경우) 클라이언트가 현재 날짜에 대한 컨텍스트를 전달하게 하고, 이를 바탕으로 학년도-학기를 확정하게 하는 것이 좋을 것 같고요, 멤버십 신청 접수하기의 경우 리쿠르팅 ID를 쿼리 파라미터로 받게 하면 이러한 문제가 해결될 것 같습니다.

@uwoobeat Post 요청 쿼리 파라미터로 열려있는 리쿠르팅 ID를 받으면 아래 두 가지에 대한 테스트는 필요 없어지므로 날짜에 대한 종속성을 제거할 수 있을 것 같네요.
```
1. 전달 받은 recruitment가 닫혀있는 경우에 대한 테스트 추가
2. 전달 받은 recruitment가 없는 경우에 대한 테스트 추가
```

> (조회의 경우) 클라이언트가 현재 날짜에 대한 컨텍스트를 전달하게 하고, 

한 가지 이해가 명확하지 못한 부분이 있는데, 여기에서의 조회는 대시보드에 대한 get요청을 말씀하시는거 맞나요?

2024-05-21 12:59 UTC, uwoobeat requested changes

2024-05-21 12:59 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/api/MembershipController.java
> +    public ResponseEntity<Void> receiveMembership(@RequestParam(name = "recruitmentId") Long recruitmentId) {
receive는 무언가를 받았다는 뜻인데 가입신청 접수라는 뜻과는 거리가 멀지 않을까요?

2024-05-21 12:59 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/api/MembershipController.java
> +    public ResponseEntity<Void> receiveMembership(@RequestParam(name = "recruitmentId") Long recruitmentId) {
description도 조금 더 자세히 작성해주시면 좋을듯 합니다.

2024-05-21 12:59 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> +        void Recruitment에_Membership을_생성한_적이_있다면_실패한다() {
테스트 이름이 명료하지 않은 것 같습니다.
현재가 2024년 2학기라고 했을 때 2023년 1학기 리쿠르팅에 대한 멤버십이 존재해도 실패하는 것인가요?

2024-05-21 12:59 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentCustomRepository.java
> +    Optional<Recruitment> findOpenRecruitment();
사용하지 않는 것 같은데, 제거 안하는 이유가 있을까요?

2024-05-21 12:59 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> +    class 멤버십_가입신청시 {
해당 리쿠르팅의 가입신청 기간이 아닌 경우에도 실패하는 테스트가 있어야 하지 않을까요?

2024-05-21 13:02 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/membership/api/MembershipController.java
> +    public ResponseEntity<Void> receiveMembership(@RequestParam(name = "recruitmentId") Long recruitmentId) {
'접수하다'라는 의미의 영단어라고 하면 receive나 take over정도인 것 같은데 생각나시는 단어가 있을까요?

2024-05-21 13:02 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentCustomRepository.java
> +    Optional<Recruitment> findOpenRecruitment();
대시보드쪽 리팩토링할때 사용할거라서 뒀습니다

2024-05-21 15:17 UTC, uwoobeat commented
> > 이거 처음부터 구현이 묘하게 거슬렸었는데, 지금 보니 날짜에 종속적인 기능이라 그런 것 같습니다.
> > 구현에 '오늘'이라는 기준을 넣게 되면 get 요청의 경우 멱등성을 지킬 수 없게 되며, get이 아닌 post의 경우더라도 테스트하기 어려운 코드가 만들어집니다.
> > 실제로 현재 멤버십 서비스 테스트 시 리쿠르팅을 생성할 때 NOW를 자주 사용하고 있는데, 테스트 안티패턴이므로 지양해야 합니다. 이를 위해서는 현재 시점에 종속적인 구현을 만들어서는 안됩니다.
> > (조회의 경우) 클라이언트가 현재 날짜에 대한 컨텍스트를 전달하게 하고, 이를 바탕으로 학년도-학기를 확정하게 하는 것이 좋을 것 같고요, 멤버십 신청 접수하기의 경우 리쿠르팅 ID를 쿼리 파라미터로 받게 하면 이러한 문제가 해결될 것 같습니다.
> 
> @uwoobeat Post 요청 쿼리 파라미터로 열려있는 리쿠르팅 ID를 받으면 `전달 받은 recruitment가 닫혀있는 경우에 대한 테스트 추가`에 대한 테스트는 필요 없어지므로 날짜에 대한 종속성을 제거할 수 있을 것 같네요.
> 
> > (조회의 경우) 클라이언트가 현재 날짜에 대한 컨텍스트를 전달하게 하고,
> 
> 한 가지 이해가 명확하지 못한 부분이 있는데, 여기에서의 조회는 대시보드에 대한 get요청을 말씀하시는거 맞나요?

네 대시보드 상에서 멤버십 신청하기 컴포넌트에 대하여 텍스트 값 구성할 때 현재 리쿠르팅 조회 API를 사용하게 됩니다.

2024-05-21 15:20 UTC, uwoobeat approved these changes
상수 부분의 경우 해당 PR에서 작업하기엔 좀 그런 것 같은데
지금 바로 수정하시거나, 별도 투두로 남기고 이슈 파서 작업 진행하시면 될 것 같습니다
lgtm

2024-05-21 15:20 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java
>      public static final String RECRUITMENT_NAME = "20xx학년도 1학기";
이거 지금 확인했는데 테스트에서 사용되는 상수를 글로벌에서 관리하고 있는 건가요?
글로벌 패키지의 상수 클래스들은 서비스 내부에서 사용되는 값에 대한 것입니다.
테스트에서 사용되는 상수는 테스트 디렉토리에서 별도로 관리해야 합니다.

2024-05-21 15:24 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java
>      public static final String RECRUITMENT_NAME = "20xx학년도 1학기";
테스트 디렉토리에 있는거 맞습니다.
다시 한번 확인부탁드려요.~

2024-05-21 15:39 UTC, merged