feat: Recruitment Startdate EndDate Period로 빼주기
GDSC-Hongik/gdsc-server pull request #337
Opened 2024-05-12 10:40 UTC by AlmondBreez3

## 🌱 관련 이슈
- close #330 

## 📌 작업 내용 및 특이사항
-

## 📝 참고사항
- validation 테스트할때 startdate, endDate일부로 given에 변수 선언 해두었는데  적절한가?..싶어서 일단 의견 여쭈어봅니당

## 📚 기타
-

2024-05-12 11:25 UTC, Sangwook02 requested changes
확인했습니다~

2024-05-12 11:25 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java
test에서 활용한다면 test에 있는 global.common.constant 디렉토리에 있는게 맞는 것 같습니다.

2024-05-12 11:25 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
> +    WRONG_DATE_ORDER(HttpStatus.BAD_REQUEST, "시간 설정이 잘못되었습니다.");
종료일이 시작일 앞일 수 없다는 것을 message에 더 자세히 적어주면 좋을 것 같아요~

2024-05-12 11:25 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentTest.java
> +            // when
```suggestion
            // when & then
```

2024-05-12 11:25 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentTest.java
> +import static com.gdschongik.gdsc.global.common.constant.MemberConstant.*;
사용하지 않는 것 같습니다

2024-05-12 11:25 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/Period.java
> +    private static void validateDate(LocalDateTime startDate, LocalDateTime endDate) {
이건 change request는 아니고 의견인데요,,
하나의 날짜를 검증하는게 아니라 period 자체를 검증하는거면 validatePeriod가 맞지 않을까요?
validateDate로 하신 이유가 있나요?

2024-05-12 11:25 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/Period.java
> +        }
이것 역시 change request는 아니고 궁금한 점인데, 시작일과 종료일이 같은 경우는 어떻게 되어야 할까요?
이 부분도 Period의 주요 정책이라고 생각되는데 test를 만들어야 하지는 않을까요🤔

2024-05-12 11:34 UTC, Sangwook02 commented
참고사항에 남겨주신 부분도 확인했는데요,
given이 꼭 있어야 할 필요는 없을 것 같아요.

2024-05-12 12:29 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/Period.java
> +    private static void validateDate(LocalDateTime startDate, LocalDateTime endDate) {
아! Period로 바꾸겠습니다 놓친 부분입니다

2024-05-12 14:09 UTC, uwoobeat requested changes
VO의 동등성에 대해서도 고민해보시면 좋을듯 합니다.

2024-05-12 15:17 UTC, AlmondBreez3 commented
> VO의 동등성에 대해서도 고민해보시면 좋을듯 합니다.

넵!!

2024-05-13 09:03 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/Period.java
> +        }
시작일과 종료일이 같으면 에러가 나야하는 것 같은데 동의하시나요?

2024-05-13 11:24 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/Period.java
> +        }
네👍

2024-05-13 11:42 UTC, Sangwook02 requested changes
이 부분까지만 해결되면 저는 approve 할 수 있을 것 같습니다!
한번만 더 확인해주세요~

2024-05-13 11:42 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
> +    WRONG_DATE_ORDER(HttpStatus.BAD_REQUEST, "시간 설정이 잘못되었습니다. 종료일이 시작일보다 같거나 앞설 수 없습니다.");
```suggestion
    WRONG_DATE_ORDER(HttpStatus.BAD_REQUEST, "종료일이 시작일과 같거나 앞설 수 없습니다.");
```

++ WRONG_DATE_ORDER보다 좋은 이름 뭐 없을까요..
마땅한게 떠오르진 않는데 `WRONG_DATE_ORDER`는 message와 맞지 않는 것 같아요..

2024-05-13 11:42 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentTest.java
다른 모든 테스트와 같은 문장 형식이면 좋을 것 같아요.
'~~~하면 성공한다. / 실패한다.'처럼요!

2024-05-13 11:42 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java
> +    public static final LocalDateTime END_DATE = LocalDateTime.of(2024, 3, 11, 00, 00);
이 테스트 상수들은 향후 요구사항이 추가되면 테스트가 깨지는 현상을 유발할 수 있을 것 같아요.

예를 들어, Period의 startDate가 현재보다 과거일 수 없다는 요구사항이 추가된다면 LocalDateTime.now()보다 상수들이 과거이므로 테스트가 깨질 수 있겠죠?

그래도 이 PR에 바로 이어서 제가 Recruitment 쪽 api 작업을 하게될테니 그때 제가 같이 개선하겠습니다!
고생하셨습니다.

2024-05-13 12:07 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
> +    WRONG_DATE_ORDER(HttpStatus.BAD_REQUEST, "시간 설정이 잘못되었습니다. 종료일이 시작일보다 같거나 앞설 수 없습니다.");
이거 지금부터 조금 생각해보겠습니다!

2024-05-13 12:34 UTC, uwoobeat requested changes

2024-05-13 12:34 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentTest.java
> +    class Period생성시 {
RecruitmentTest 클래스에서 Period에 대한 테스트를 작성하는 것은 올바르지 않은 것 같습니다.

2024-05-13 12:37 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentTest.java
> +    class Period생성시 {
그러면 Period테스트 클래스로 따로 뺴서 테스트 작성하겠습니다

2024-05-13 13:01 UTC, uwoobeat requested changes

2024-05-13 13:01 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentTest.java
> +        void 잘못된_Period_순서_입력되면_생성_실패한다() {
Period 테스트에서 이미 검증된 테스트를 리쿠르팅에서 중복해서 검증할 필요는 없을 것 같습니다~

2024-05-13 13:15 UTC, uwoobeat approved these changes
lgtm
PR 제목만 작업내용이 잘 드러나게 작성해주시면 될듯 합니다

2024-05-13 13:17 UTC, merged