feat: exception handling
GDSC-Hongik/gdsc-server pull request #34
Opened 2024-01-30 07:43 UTC by Sangwook02

## 🌱 관련 이슈
- close #16

## 📌 작업 내용 및 특이사항
- GlobalExceptionHandler로 CustomException, RuntimeException 처리
- ErrorResponse, ErrorCode 추가
- JwtFilter에서 발생하는 Exception을 처리할 JwtExceptionFilter 추가

2024-01-30 12:36 UTC, uwoobeat requested changes

2024-01-30 12:36 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/global/util/JwtUtil.java
> -            return null;
null로 리턴하는거 의도한 부분인데 수정한 이유가 있나요?

2024-01-30 12:36 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/auth/application/JwtService.java
>      public AccessTokenDto retrieveAccessToken(String accessTokenValue) {
제거 의도가 궁금합니다~

2024-01-30 13:37 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/global/util/JwtUtil.java
> -            return null;
만료 이외의 예외는 null을 반환해서 재발급 과정을 거치기보다 예외를 던지는 것이 적절한 것 같아 수정했습니다!

2024-01-30 13:38 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/auth/application/JwtService.java
>      public AccessTokenDto retrieveAccessToken(String accessTokenValue) {
이 부분은 제가 착각했습니다.
아래와 같이 수정하는 게 좋겠네
```java
try {
      return jwtUtil.parseAccessToken(accessTokenValue);
} catch (ExpiredJwtException e) {
      return null;
}

2024-01-30 14:17 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/global/util/JwtUtil.java
> -            return null;
만료 이외의 예외가 발생해서 `JwtFilter` 의 line 52 로직을 타더라도, `reissueAccessTokenIfExpired` 에서 `ExpiredJwtException` 에 잡히지 않아 null로 반환되기 때문에 `isPresent` 로직을 타지 않아서 재발급이 이루어지지 않습니다.

로직 다시 한번 체크해보실래요?

2024-01-31 04:58 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/global/util/JwtUtil.java
> -            return null;
잡히지 않는 이유를 확인해본 결과,
`reissueAccessTokenIfExpired`에 AT가 아닌 RT를 넘겨서 `ExpiredJwtException`이 아닌 `SignatureException`이 발생하는 것이 원인이었습니다.

이외에도 `JwtService.getRefreshTokenFromRedis`의 내부를 조금 수정했으니 같이 확인 부탁드립니다!

2024-01-31 05:04 UTC, uwoobeat approved these changes
어푸루부를드릴게요

2024-01-31 05:05 UTC, merged