refactor: member domain grant() 멤버 상태 변경
GDSC-Hongik/gdsc-server pull request #340
Opened 2024-05-13 12:17 UTC by AlmondBreez3

## 🌱 관련 이슈
- close #339 

## 📌 작업 내용 및 특이사항
- 원래는 payment까지 없애려고 했는데 연결된 부분들이 많아서 grant()시 USER -> ASSOCIATE로 변경하는 부분만 바꾸고 테스트 코드도 변경하였습니당~

## 📝 참고사항
-

## 📚 기타
-

2024-05-13 13:06 UTC, Sangwook02 requested changes
하나만 확인해주세요~

2024-05-13 13:06 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        return role.equals(ASSOCIATE) || role.equals(MemberRole.ADMIN);
isGranted 메서드는 디스코드에서 사용되는 `가입하기` 커맨드에서 사용됩니다. 
해당 명령어가 deprecated이긴해도 이번 학기가 끝날때까지는 정상 작동해야 하는데, isGranted에서 USER를 완전히 제거해버리면 명령어가 정상 작동하지 않습니다.

일단은 USER, ASSOCIATE, ADMIN 을 모두 grant의 조건으로 취급해야 할 것 같습니다.

2024-05-13 13:07 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        return role.equals(ASSOCIATE) || role.equals(MemberRole.ADMIN);
`JoinCommandHandler`를 열어보시면 이해에 도움이 될 것 같아요

2024-05-13 13:08 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        return role.equals(ASSOCIATE) || role.equals(MemberRole.ADMIN);
네 그리고 코드에 todo로 USER 제거에 대해 남겨주시면 좋을 것 같네요!

2024-05-13 13:09 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        return role.equals(ASSOCIATE) || role.equals(MemberRole.ADMIN);
넵!

2024-05-13 13:19 UTC, uwoobeat requested changes
변경된 정책에서 사용되는 워딩은 반영이 안된건가요?
가령 guest -> associate 과정을 signup으로 했었는데, 여기서는 grant인 것 같습니다.

2024-05-13 13:28 UTC, AlmondBreez3 commented
> 변경된 정책에서 사용되는 워딩은 반영이 안된건가요? 가령 guest -> associate 과정을 signup으로 했었는데, 여기서는 grant인 것 같습니다.



> 변경된 정책에서 사용되는 워딩은 반영이 안된건가요? 가령 guest -> associate 과정을 signup으로 했었는데, 여기서는 grant인 것 같습니다.

sign up 말고 grant로 사용하려고 하는데 이에 대한 것은 노션에 더 자세히 바꿔서 카톡이나 슬랙에 말씀드릴게요

2024-05-14 14:21 UTC, Sangwook02 approved these changes
lgtm

2024-05-22 12:35 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +    class 재학생_인증시 {
수정했습니다~

2024-05-22 12:38 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +    class 재학생_인증시 {
push를 안 하신 것 같네요?

2024-05-22 12:40 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +    class 재학생_인증시 {
앗 안돼있나요? 잠시만요

2024-05-22 12:40 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +    class 재학생_인증시 {
아 그 actions 실패했네요

2024-05-22 12:41 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +    class 재학생_인증시 {
디벨롭 풀 해오고 다시 푸쉬 하겠슴다~

2024-05-22 13:07 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +    class 재학생_인증시 {
넵

2024-05-22 13:09 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
> -    @Operation(summary = "승인된 회원 전체 조회", description = "승인된 회원 전체를 조회합니다.")
아 ! 이거 api는 당장 존재하는 것만 바꿔주는 거라서 고려를 자세히 안했습니다! 따로 이슈 파서 하는게 맞는것 같아서..!
혹시 의견있으실까용? 그냥 한번에 여기다가 할까요?

2024-05-22 13:10 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    // TODO deprecated방식
지워야 하는데 안지웠습니다...감사합니다

2024-05-22 13:11 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
> -    @Operation(summary = "승인된 회원 전체 조회", description = "승인된 회원 전체를 조회합니다.")
저는 있는게 맞는 것 같아요.
자세한 부분은 슬랙에서 기획팀이랑 논의해보시고 기획팀에서 필요하다고 하시면 이슈 새로 만들어주시면 될 것 같습니다.

2024-05-27 10:20 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +    class 재학생_인증시 {
> MemberTest의 `가입_신청_시`를 보시면 MemberRole, MemberStatus라는 표현을 사용하고 있습니다. 참고해서 수정하시면 좋을 것 같습니다.

다시 봐주셔야 할 것 같습니다.

2024-05-27 10:45 UTC, Sangwook02 requested changes
확인했습니다

2024-05-27 10:45 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +    class 재학생_인증시 {
재학생 인증도 line 45의 회원 가입 과정의 일부인데 이것만 별도의 class로 빼낸 이유가 있나요?

2024-05-27 10:45 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        return role.equals(ASSOCIATE) || role.equals(MemberRole.ADMIN) || role.equals(REGULAR);
```suggestion
        return role.equals(ASSOCIATE) || role.equals(ADMIN) || role.equals(REGULAR);
```

2024-05-27 10:45 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +     *
```suggestion
     * 가입 신청 시 작성한 정보를 저장한다.
```

2024-05-27 10:45 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
>      public void signup(String studentId, String name, String phone, Department department, String email) {
구버전 signUp 메서드를 사용하고 있는 test들이 MemberRepositoryTest에 있네요.
ex) `역할로_조회할때.승인전이라면_GUEST로_조회된다`


이 부분은 별도 이슈 생성해주세요~

2024-05-27 10:56 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +    class 재학생_인증시 {
저도 짜면서 좀 고민했던 부분인데 회원가입(전체) 따로, 디스코드 연동 확인 따로, Bevy인증 따로, 재학생 인증 따로 이렇게 할지 아니면 그냥 회원가입(전체)만 구현해도 될지 고민중이었는데..중복되는 것 같아서 저도 고민했습니다! 단지 각각의 인증시 어떤 상태로 바뀌는지에 대해 자세한 명세가 필요할까?하면서 구현해둔 거였습니다

2024-05-27 10:58 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
>      public void signup(String studentId, String name, String phone, Department department, String email) {
구버전 다 삭제하라는 말씀이신가용?? 아니면 지금의 signUp으로 바꾸어둘까요?

2024-05-27 11:02 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
>      public void signup(String studentId, String name, String phone, Department department, String email) {
다시보니 각 테스트에서 signUp 메서드 사용한 한 줄만 지우면 될 것 같네요?
굳이 이슈 생성할 필요 없이 여기에서 처리해주셔도 될 것 같습니다.

2024-05-27 11:05 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +    class 재학생_인증시 {
아 그렇군요
아래에 디스코드와 베비 관련 클래스도 있는 걸 못 보고 3가지 조건 중에 재학생 인증만 빼내신 줄 알았습니다.
제가 잘못 봤네요😅

2024-05-27 11:06 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
>      public void signup(String studentId, String name, String phone, Department department, String email) {
구버전이 signup
현재가 signUp인데
구버전 signup말씀하신거 맞으시죠?

2024-05-27 11:06 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
>      public void signup(String studentId, String name, String phone, Department department, String email) {
네 맞습니다~

2024-05-27 14:01 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
>      public void signup(String studentId, String name, String phone, Department department, String email) {
상욱님 제가 저 부분 signup이랑 completeUnivEmail지워보면 아예 에러가 뜨는데 혹시 시간 되시면 확인해보실 수 있을까요?

2024-05-27 14:34 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
>      public void signup(String studentId, String name, String phone, Department department, String email) {
<img width="596" alt="image" src="https://github.com/GDSC-Hongik/gdsc-server/assets/99820610/6d84d393-7e9e-4524-bfa8-49167380da3a">
<img width="619" alt="image" src="https://github.com/GDSC-Hongik/gdsc-server/assets/99820610/149c2463-67cd-4910-a519-fc38c171a396">

이 부분에서 저 두 테스트 코드를 추가했는데 실패하더라고요. findAllgrantable이 회원가입완료, 즉 모든 조건을 만족 시킨 사람들을 조회한다는것인가요?

2024-05-28 01:28 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
>      public void signup(String studentId, String name, String phone, Department department, String email) {
그러고 보니 새로운 로직에서는 승인 가능한 멤버 조회 기능이 필요없으니 무의미한 테스트 아닌가요?

2024-05-28 13:45 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
>      public void signup(String studentId, String name, String phone, Department department, String email) {
그러네욥 지워도 될것 같습니다.

2024-05-28 15:11 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +    class 재학생_인증시 {
다시 확인해주세요
Member_Role처럼 기존 코드랑 안 맞는 부분이 아직 남아있습니다.

2024-05-28 16:08 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +    class 재학생_인증시 {
으앗 계속 달고 계신지 몰랐습니다 카멜케이스로 바꿔서 커밋했ㅂ니다!다음부터는 꼼꼼히 살펴보겠습니다

2024-05-29 08:14 UTC, Sangwook02 requested changes
다시 리뷰했습니다~

2024-05-29 08:14 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    public void signUp() {
기존의 signup이 존재하더라도,
파라미터 개수로 구, 신 signup을 구분할 수 있기도 하고
팀에서 사용해온 용어가 있는 상황에서 signUp을 사용해야 할 필요가 있나 싶습니다.

구버전 메서드에 사라질 예정이라는 내용의 주석만 잘 달아준다면 새로운 버전의 메서드도 signup으로 가도 괜찮지 않나요?

2024-05-29 10:38 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    public void signUp() {
저는 그게 좋다고 생각합니다!!

2024-05-29 10:42 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +        void 회비납부_디스코드인증_Bevy인증_재학생인증하면_성공한다() {
이거 보고 생각이 난건데 회비납부시 탈퇴한 유저면 실패한다라는 테스트는 사용하지 않는 메서드에 대한 테스트인 셈인데 지우는 것이 맞다고 생각하는데 어떻게 생각하시나요?

2024-05-29 10:56 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +        void 회비납부_디스코드인증_Bevy인증_재학생인증하면_성공한다() {
네 근데 일단 이슈 크기가 더 커지면 리뷰하기가 어려울 것 같아서
멤버의 회비 관련 메서드를 제거하는 작업은 별도의 이슈를 만들어서 처리하는게 좋을 것 같습니다~

2024-05-31 11:58 UTC, Sangwook02 requested changes

2024-05-31 11:58 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberServiceTest.java
> +        void 기본회원정보_작성을_완료헀다면_성공한다() {
```suggestion
        void 기본_회원정보_작성을_완료헀다면_성공한다() {
```

이 파일과 MemberRepositoryTest에 5~6개 정도 있는 것 같아요.
같이 확인부탁드려요.
'기본회원정보'로 찾아서 처리하시면 편할 것 같네요.

2024-05-31 11:58 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
`준회원_승급가능_멤버를_조회할때`, `기본회원정보_작성후_준회원_승급전_이라면_GUEST로_조회된다` 등은 정책 변경으로 인해 존재 의미가 없는 메서드인 것 같아요.
Member관련 테스트 중에 이외에도 정책 변경으로 인해 무의미해진 케이스가 꽤 있을 것 같으니 별도 이슈 만들어주세요!

2024-05-31 11:58 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +        void 준회원_승급조건이_모두_만족됐으면_MemberRole은_ASOOCIATE이다() {
```suggestion
        void 준회원_승급조건이_모두_만족됐으면_MemberRole은_ASSOCIATE이다() {
```

같은 오타가 몇 개 더 있네요.

2024-05-31 13:48 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberServiceTest.java
> +        void 기본회원정보_작성을_완료헀다면_성공한다() {
헉 저 이게 push가 안된것 같아용 왜지..?? 저 분명 로컬에는 다 기본회원정보로 되어있어서 ㅎㅎ..

2024-05-31 13:54 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberServiceTest.java
> +        void 기본회원정보_작성을_완료헀다면_성공한다() {
<img width="754" alt="image" src="https://github.com/GDSC-Hongik/gdsc-server/assets/99820610/bc699412-8f14-4309-9774-ae706d67e37b">

안된것 같아서 다시 add해보니까 nothing new이런식으로 뜨는데 혹시 무슨 오륜지 아실까요?

2024-05-31 13:56 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
확인했습니답

2024-05-31 13:56 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
> +        void 준회원_승급조건이_모두_만족됐으면_MemberRole은_ASOOCIATE이다() {
헉 확인하고 올리겠습니다

2024-06-01 07:30 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberServiceTest.java
> +        void 기본회원정보_작성을_완료헀다면_성공한다() {
리뷰 내용 다시 확인해주세요.

2024-06-01 08:19 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberServiceTest.java
> +        void 기본회원정보_작성을_완료헀다면_성공한다() {
아 저 부분 _에 대해서는 수정했는데 제가 _말고는 다 제대로 하고 푸쉬했는데 커밋이 안날린 문제에 대해서 말씀드린거에용!
그 pr리뷰는 이미 반영한 상태입니다~

2024-06-01 11:33 UTC, Sangwook02 requested changes
저는 이게 마지막인 것 같습니다.

2024-06-01 11:33 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
>      }
isAssociate라는 메서드명을 가지고 있지만, REGULAR와 ADMIN도 true를 반환합니다.
이 메서드의 핵심은 `멤버가 최소한 ASSOCIATE 이상의 권한을 가지고 있는지를 확인하는 것`이니,
더 적절한 메서드명이 있을지 직접 생각해보시면 좋을 것 같습니다.

2024-06-01 11:33 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
> +        void 기본_회원정보_작성후_준회원_승급후_이라면_ASSOCIATE로_조회된다() {
```suggestion
        void 기본_회원정보_작성후_준회원_승급후라면_ASSOCIATE로_조회된다() {
```

2024-06-02 03:17 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
>      }
checkIfAssociateOrHigher
한번 더 생각해볼까요?

2024-06-02 12:39 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
>      }
`isAtLeastAssociate` 같은 것도 괜찮을 것 같습니다.

2024-06-02 15:06 UTC, uwoobeat requested changes

2024-06-02 15:06 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
> +    @PostMapping("/update-basic-info")
특수한 경우가 아니라면 rest api 설계 시 동사는 넣지 않습니다~

2024-06-02 15:06 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    public void updateBasicMemberInfo(
기본 회원정보 작성도 준회원 가입조건으로 들어갔는데 반영이 안된 것 같습니다

2024-06-02 15:10 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
> +    @PostMapping("/update-basic-info")
바꾸겠습니당

2024-06-03 09:32 UTC, uwoobeat approved these changes
verify로 통합될 예정이므로 동일하게 `/me/basic-info` 로 맞춰주시면 좋을 것 같습니다~

2024-06-03 11:05 UTC, Sangwook02 approved these changes
pr 제목에 `회원가입`보다는 `준회원 승급`이 맞지 않을까 싶네요
일단 approve 해두겠습니다.

2024-06-03 11:36 UTC, merged