feat: Recruitment 생성 API 구현
GDSC-Hongik/gdsc-server pull request #345
Opened 2024-05-22 13:04 UTC by Sangwook02

## 🌱 관련 이슈
- close #333

## 📌 작업 내용 및 특이사항
- `academicYear`와 `semesterType`을 dto로 받을지 고민이었는데 일단은 모집기간 시작일을 기준으로 서버에서 처리하도록 구현했습니다.
- 검증해야 할 사항은 두가지 입니다. 
  1. 기간이_중복되는_Recruitment가_있다면_실패한다
  2.  신청 시작일과 종료일은 모두 미래의 시점이다.

2번의 경우 dto에서 어노테이션으로 검증되는 부분이라 test를 작성하지는 않았습니다.

## 📝 참고사항
-

## 📚 기타
-

2024-05-25 07:36 UTC, AlmondBreez3 approved these changes
lgtm

2024-05-25 07:36 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/api/AdminRecruitmentController.java
> +@RestController
저희 근데 리크루팅으로 하자고 하지 않았나용? 기억이 안나네욥

2024-05-26 11:58 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/api/AdminRecruitmentController.java
> +@RestController
너무 길다고 '리쿠르팅' 쓰기로 했던 것 같아요.
테이블 명이랑 안 맞는게 좀 아쉽긴하지만 swagger 문서에는 모두 리쿠르팅으로 변경하겠습니다.

2024-05-26 12:21 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/api/AdminRecruitmentController.java
> +@RestController
넵넵 리크루팅은 단지 프론트/기획/백엔드 용어 통일을 위해 정한 것 같고 영어로 recruitment는 이게 리쿠르팅이다 라는것을 저희가 백끼리 이해만 하면될거같아요

2024-05-28 12:43 UTC, uwoobeat requested changes

2024-05-28 12:43 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/common/model/SemesterType.java
> +        if (dateTime.getMonthValue() < 7) {
해당 조건도 추출해서 의미있는 이름으로 만들면 좋을듯 합니다.

2024-05-28 12:43 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/request/RecruitmentCreateRequest.java
> +        @NotBlank @Schema(description = "이름") String name,
학년 / 학기 정보를 클라이언트로부터 받는게 낫지 않을까요?
그리고 시작일 / 종료일이 해당 학년 / 학기 정보에 대하여 유효한지 validate만 하면 될 것 같습니다.

2024-05-29 13:18 UTC, Sangwook02 commented
정회원들을 준회원으로 강등하는 로직이 빠졌네요.
작업 후에 다시 리뷰 요청 드리겠습니다.

2024-06-02 10:11 UTC, uwoobeat requested changes

2024-06-02 10:11 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/common/model/SemesterType.java
> +        return getSemesterType(dateTime);
분리하신 이유가 있나요?

2024-06-02 10:11 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/common/model/SemesterType.java
> +        LocalDateTime firstSemesterStartDate = LocalDateTime.of(year, 3, 1, 0, 0, 0);
매직 넘버는 상수로 추출해주세요~ 
ex) 3월 1일, 2주, 7월

2024-06-02 13:42 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/common/model/SemesterType.java
> +        return getSemesterType(dateTime);
> 해당 조건도 추출해서 의미있는 이름으로 만들면 좋을듯 합니다.

분리하자는 의미 아니었나요?

2024-06-02 13:48 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/common/model/SemesterType.java
> +        LocalDateTime firstSemesterStartDate = LocalDateTime.of(year, 3, 1, 0, 0, 0);
3월 1일과 9월 1은 아래와 같이 처리하면 좋을 것 같네요👍👍
```
public enum SemesterType {
    FIRST("1학기", MonthDay.of(3, 1)),
    SECOND("2학기", MonthDay.of(9, 1));

    private final String value;
    private final MonthDay startDate;
}
```

2024-06-02 14:59 UTC, uwoobeat requested changes

2024-06-02 14:59 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/common/model/SemesterType.java
> +    public static SemesterType from(LocalDateTime dateTime) {
해당 메서드가 적절한 책임을 가지지 못하는 것 같습니다.

저라면 이 메서드를 보고 "대충 enum 멤버로 학기 시작일이 있으니까, 인자로 받은 dateTime이 학기 시작일 ~ 종료일 사이이면 해당 학기타입을 반환하겠구나?" 라고 생각할 것 같아요.

그런데 실제 로직을 보면 학기 시작일 2주 전에 해당하는 dateTime도 해당 학기타입으로 매핑해주고 있습니다. 이렇게 하면 처음 보는 사람은 조금 혼란스러울 것 같다는 생각이 듭니다.


저희가 이렇게 했던 이유가 뭐였나요? 인자로 들어오는 값이 리쿠르팅의 시작일과 마감일이었기 때문이었죠.

여기서 두 가지 문제가 있는데요,

1. SemesterType의 내부 로직이, 이러한 리쿠르팅에 의존적인 컨텍스트 정보를 알 필요가 없고, 안다 하더라도 리쿠르팅이 가져야 할 책임을 학기타입이 가져가는 것이기 때문에 SRP 위반이고요,
2. `SemesterType::from` 으로 들어오는 값이 항상 리쿠르팅의 시작일과 마감일이라는 보장이 없다는 겁니다. 다른 로직에서 언제든지 실수하고 아, LocalDateTime을 SemesterType으로 매핑해주는 정적 메서드구나 하고 쓸 여지가 많습니다.

2번의 경우 인자를 Recruitment로 받거나 하면 해결될 수 있지만 1번을 해결 못했기 때문에 근본적인 해결책은 아니죠.
결국 학기타입 매핑 로직은 리쿠르팅 서비스로 빼내는 것이 적절해보입니다.

2024-06-02 15:02 UTC, uwoobeat requested changes

2024-06-02 15:02 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/common/model/SemesterType.java
> +        if (dateTime.isAfter(firstSemesterStartDate.minusWeeks(TWO_WEEKS)) && dateTime.getMonthValue() < JULY) {
그리고, "리쿠르팅의 경우 개강일 전에 시작하므로, 리쿠르팅 시작일이 2주 전이더라도 1학기로 매핑한다" 같은 식의 컨텍스트 정보를 주석에 쓰는 것도 나쁘지 않을 것 같아요. 저는 정책적인 부분은 주석으로 남기는 거 충분히 의미있다고 생각합니다.

리쿠르팅 시작이 2주 전이라는 것도 뭔가 빡빡해보이는데, 2주로 할지 4주로 할지에 대한 것도 운영진 쪽에서 컨펌받고 진행해야 하지 않을까 싶네요~

2024-06-03 04:41 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/common/model/SemesterType.java
> +        if (dateTime.isAfter(firstSemesterStartDate.minusWeeks(TWO_WEEKS)) && dateTime.getMonthValue() < JULY) {
2주라는 기간은 운영진과 협의해서 정한 부분입니다!

2024-06-03 05:34 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/common/model/SemesterType.java
> +    public static SemesterType from(LocalDateTime dateTime) {
그렇네요.
저도 SemesterType.from이 항상 LocalDateTime만 받는게 맞을지, 그리고 받는 LocalDateTime에 대해 항상 같은 로직으로 SemesterType을 반환하는게 맞을지에 대한 고민이 있었는데 서비스로 옮기니 마음에 걸리던데 해소된 느낌이네요👍

2024-06-03 13:34 UTC, uwoobeat requested changes

2024-06-03 13:34 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/api/AdminRecruitmentController.java
> +@RequestMapping("/admin/recruitment")
```suggestion
@RequestMapping("/admin/recruitments")
```

2024-06-03 13:34 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
> +        if (dateTime.isAfter(firstSemesterStartDate.minusWeeks(TWO_WEEKS)) && dateTime.getMonthValue() < JULY) {
해당 상수명을 TWO_WEEKS로 하면 나중에 3주나 4주로 정책이 변경되었을 때 상수명을 전부 바꿔야 하지 않을까요?
상수에도 적절한 이름을 붙여야 할 것 같습니다.

2024-06-04 13:04 UTC, uwoobeat requested changes

2024-06-04 13:05 UTC, uwoobeat approved these changes
lgtm
위 내용만 수정하시면 될 것 같습니다.

2024-06-04 13:05 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
> +    RECRUITMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "열려있는 리크루트먼트가 없습니다."),
한글 워딩은 '리쿠르팅'으로 통일해야 합니다. 해당 건은 별도 이슈로 작업하셔도 됩니다

2024-06-04 13:08 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
> +    RECRUITMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "열려있는 리크루트먼트가 없습니다."),
전범위로 검색해보니 여기에만 있네요
자잘한 부분이니 여기서 처리할게요
꼼꼼히 봐주셔서 감사드려요

2024-06-04 13:17 UTC, merged