feat: Recruitment 조회 API 구현
GDSC-Hongik/gdsc-server pull request #352
Opened 2024-06-07 11:44 UTC by Sangwook02

## 🌱 관련 이슈
- close #334

## 📌 작업 내용 및 특이사항
- 아래는 이 조회 api의 요구사항입니다.
   - `학년도 내림차순 -> 학기 내림차순으로 정렬합니다.`
   - `학년도와 학기가 같다면, 모집 시작일이 빠른순(1차, 2차, … )으로 정렬합니다.`
- `학년도와 학기가 같다면, 모집 시작일이 빠른순(1차, 2차, … )으로 정렬`을 하기 위해서 그룹화가 필요합니다. 
이때 `Collectors.groupingBy()`의 파라미터로 아래와 같이 구현하면 Map<Map<>>의 구조가 되어버려서 이후의 로직에서 이중 forEach를 사용하게 됩니다.
```
Collectors.groupingBy(recruitment ->
                    recruitment.getAcademicYear(), Collectors.groupingBy(Recruitment::getSemesterType))
```
이를 개선하기 위해서 AcademicYearSemesterKey라는 record를 만들어서 그룹화에 활용했습니다.
자세한 코드는 `AdminRecruitmentService.recruitmentsGroupByAcademicYearAndSemesterType` 메서드에서 확인해주시면 좋을 것 같습니다.

## 📝 참고사항
-

## 📚 기타
-

2024-06-09 08:54 UTC, uwoobeat reviewed
그런데 이렇게 했을 때 페이징에 문제는 없나요?
결국은 한 페이지 내에서 정렬을 다시 하는 구조라,
전체 대상에서 정렬하고 -> 페이지네이션은 아니라서 잘 작동할지는 모르겠네요.

2024-06-13 09:27 UTC, uwoobeat requested changes

2024-06-13 09:27 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
> +                    int round = recruitmentList.indexOf(recruitment) + 1;
회차정보인거죠?
직접 계산하는 것보다는 리쿠르팅 내부적으로 가지고 있는게 나을 것 같습니다

2024-06-13 09:30 UTC, uwoobeat commented
그리고 쿼리 정렬 사용하지 않고 애플리케이션 레이어에서 정렬 구현하신 이유가 궁금합니다

2024-06-14 14:36 UTC, uwoobeat approved these changes
vo 사용하면 response 매핑해줄 때 npe 가능성이 있어서, 요거 datasource 설정에 추가해주세요
`spring.jpa.properties.hibernate.create_empty_composites.enabled=true`

2024-06-14 14:37 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentCustomRepositoryImpl.java
> +    public List<Recruitment> findAllOrderByStartDate() {
data jpa로도 가능한 쿼리이지 않을까 싶습니다

2024-06-15 02:00 UTC, AlmondBreez3 approved these changes
lgtm

2024-06-15 02:01 UTC, merged