feat: 상태별 회원 조회 목록 api구현 및 간단 repository test
GDSC-Hongik/gdsc-server pull request #371
Opened 2024-06-11 14:45 UTC by AlmondBreez3

## 🌱 관련 이슈
- close #344 

## 📌 작업 내용 및 특이사항
- 이미 기존에 존재하는 전체 회원 조회..이미 사용되고 있는 api이므로 일단 deprecated로 냅두고 /role?role=guest이런식으로 받도록 했습니다
- updatePaymentStatus에 수정한 REGULAR로 바꾸는 코드는 일단 아직 제대로 된 결제 로직이 없으니까 임시로 만들어 두고 나중에 결제 쪽 할 때 바꾸시면 될듯합니다아

## 📝 참고사항
-

## 📚 기타
-

2024-06-11 16:50 UTC, uwoobeat reviewed
동일 api에서 멤버 역할만 검색 옵션으로 추가하면 될듯 한데 별도 api로 분리하신 이유가 있나요?

2024-06-11 19:10 UTC, Sangwook02 requested changes
확인했습니다

2024-06-11 19:10 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
> +    @GetMapping("/role")
기존 메서드가 admin  페이지에서 계속 사용되기는 합니다만, 
쿼리 파라미터만 추가하면 영향을 주지 않고 수정이 가능할 것 같습니다.

2024-06-11 19:10 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
> +            member.updatePaymentStatus(VERIFIED);
이 메서드는 곧 사라질 예정이라 test에서 사용하지 않는게 좋을것 같습니다~

2024-06-12 03:17 UTC, AlmondBreez3 commented
> 동일 api에서 멤버 역할만 검색 옵션으로 추가하면 될듯 한데 별도 api로 분리하신 이유가 있나요?

아 그 이미 기존에 사용되던거라서 일단 건드리지 않으려고 한건데 밑에 상욱님이 남겨주신거보면 기존 api를 수정하는 방향으로 가져가도 될것같습니다
수정해서 다시 푸쉬하겠습니다.

2024-06-12 03:18 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
> +            member.updatePaymentStatus(VERIFIED);
updatePayment말씀하시는거죠? 결제 쪽에서 이거 그대로 사용하실거라고 들어서..혹시 모르니까 그냥 이 테스트는 삭제할까요?

2024-06-13 11:41 UTC, Sangwook02 requested changes
확인했습니다!

2024-06-13 11:41 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
> +    @Operation(summary = "회원 상태별 목록 조회", description = "정회원, 준회원, 게스트별로 조회합니다.")
MemberRole도 있고 MemberStatus도 있으므로 아래와 같이 바꾸는 게 좋을 것 같습니다.
pr 제목도 같이 부탁드립니다~
```suggestion
    @Operation(summary = "회원 역할별 목록 조회", description = "정회원, 준회원, 게스트별로 조회합니다.")
```

2024-06-13 11:41 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
> +            member.updatePaymentStatus(VERIFIED);
네 updatePaymentStatus 말씀드린거 맞아요
재현님께서 작업하신 내용이 이미 dev에 들어가있어서 conflict가 생겼네요
확인부탁드려요

2024-06-13 14:54 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
> +    @Operation(summary = "회원 상태별 목록 조회", description = "정회원, 준회원, 게스트별로 조회합니다.")
앗 알겠습니다~~

2024-06-13 14:54 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
> +            member.updatePaymentStatus(VERIFIED);
넵 그 재현님 pr다 되고 그거 가져다가 작업하라고 하셔서 기다리고 있던 상태였습니당

2024-06-14 07:07 UTC, Sangwook02 approved these changes
lgtm

2024-06-15 11:58 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    public void updatePaymentStatus(RequirementStatus status) {
이거 merge되면서 문제 생겼나봐요..!! 왜 저기에 들어갔는지 모르겠네요 지우겠습니다

2024-06-15 12:12 UTC, uwoobeat approved these changes
lgtm

2024-06-15 12:53 UTC, merged