refactor: 기존 가입조건을 준회원 승급조건 및 정회원 승급조건 VO로 분리
GDSC-Hongik/gdsc-server pull request #375
Opened 2024-06-11 18:23 UTC by uwoobeat

## 🌱 관련 이슈
- close #360 

## 📌 작업 내용 및 특이사항
- 멤버십에서 paymentStatus 직접 사용하고 있는 것을 없애고, 정회원 승급조건인 `RegularRequirement` VO로 관리하도록 변경했습니다.
- 기존에 `getPaymentStatus()` 로직 대신 `isAdvanceToRegularAvailable()` 을 사용하도록 변경했습니다.
    - 해당 메서드는 `RegularRequirement` 의 `isAllVerified()` 를 사용합니다.
-  `RequirementStatus` enum을 common 패키지로 이동했습니다 (승급조건이 서로 다른 패키지에서 사용되기 때문).
- 기존 `Requirement` VO의 경우 준회원 승급조건이므로 `AssociateRequirement` VO로 변경했습니다.

### 회비 납입상태에 대한 문제 (중요)
- 기존에는 `Member` 가 회비 납입상태인 `paymentStatus` 를 관리하고 있었기 때문에 문제가 없었습니다. 하지만 2차 MVP 부터는 회원이 아닌 멤버십이 해당 상태를 관리하기 때문에, 많은 스펙 변경이 발생했습니다. 
- 이때 멤버에 대하여 회비 납입상태를 어드민에서 수동으로 업데이트하고, 승인 가능하면 `grant()` 를 호출하는 기존 로직과 다르게, 현재 로직에서는 회비 납입상태의 경우 결제 서비스를 통해 자동으로 업데이트되며, `grant()` 대신 정회원 승급으로 변경되었으므로, 기존 로직은 제거하기로 결정했습니다.
- 제거된 부분은 다음과 같습니다.
    - 어드민의 `AdminMemberResponse` 에서 결제상태 제외 -> 결제상태 확인하려면 별도 탭에서 조회하는 것으로 변경. 피그마에 코멘트 추가해두었습니다. 기존 스펙을 지원하려면 Membership을 조인해야 하는데, 이렇게 하는 것보다 그냥 결제상태를 제외하는 것이 더 빠릅니다.
    - 온보딩의 내 회원정보 조회하기에서도 결제상태 제외했습니다.
    - 어드민의 회비 납부상태 토글 API 및 관련 로직을 제거했습니다.
    - 준회원 승급가능 멤버 조회 시 테스트 픽스처 세팅하는 로직이 신규 로직이 아닌 `grant()` 로직 버전으로 되어있어 해당 테스트 섹션을 일괄적으로 deprecated 처리했습니다.
- 즉 핵심은 "준회원 승급조건에서 `paymentStatus`가 사라졌고, 이를 필요로 하는 로직은 대부분 제거했다" 로 보시면 될 것 같습니다.

## 📝 참고사항
-

## 📚 기타
- 추후 `grant()` 관련 로직도 제거해야 합니다.

2024-06-11 19:21 UTC, Sangwook02 requested changes
+ RegularReq에는 `@EqualsAndHashCode`가 있는데 AssociateReq에는 없는 이유가 있다면 궁금합니다~

2024-06-11 19:21 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
> -
이 부분 한비님께서 일단은 deprecated로 해두셨는데, 프론트 작업 끝나고 제거하는게 좋지 않을까요?

2024-06-11 19:21 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberQueryMethod.java
> +                .and(eqRequirementStatus(member.associateRequirement.bevyStatus, VERIFIED));
여기는 infoStatus 필요없나요?

2024-06-11 19:21 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/dto/response/AdminMemberResponse.java
> +                    associateRequirement.getBevyStatus().name());
여기도 마찬가지로 infoStatus도 넣어야 하지 않나요?

2024-06-12 01:03 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
> -
어차피 프론트 작업은 백엔드 작업 끝나야 들어가는 거라서, 냅둬봤자 도메인 로직만 꼬이고 병목생겨서 제거하는게 좋다고 생각했습니다.
지금 현재 문제 대부분은 grant 로직과 payment status 때문에 발생하고 있어서요.

2024-06-12 01:04 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/dto/response/AdminMemberResponse.java
> +                    associateRequirement.getBevyStatus().name());
`isGrantAvailable()` 은 사용하지 않을 것이라 결제상태만 제거했습니다.

2024-06-12 08:02 UTC, Sangwook02 approved these changes
lgtm

2024-06-12 08:17 UTC, AlmondBreez3 approved these changes
lgtm

2024-06-12 11:32 UTC, merged