feat: 멤버 탈퇴 api 구현
GDSC-Hongik/gdsc-server pull request #38
Opened 2024-02-04 13:52 UTC by Sangwook02

## 🌱 관련 이슈
- close #25 

## 📌 작업 내용 및 특이사항
- 멤버 삭제
- redis에서 토큰 삭제
- 쿠키 무효화 작업

2024-02-06 12:02 UTC, uwoobeat approved these changes
lgtm

다만 한 가지 논의해야 하는 것이... soft delete vs hard delete인데요,
서버끼리 한번 이야기해봐야 할 것 같습니다.

2024-02-08 07:57 UTC, Sangwook02 reviewed
soft delete 하도록 수정했습니다

2024-02-09 06:38 UTC, uwoobeat requested changes
멤버 탈퇴 시 재가입이 가능하도록 로그인 `fetchOrCreate` 쪽 로직에서 멤버 fetch할 때 일반 상태만 가져오도록 해서, deleted인 경우 create 로직 타도록 변경해주세요.

2024-02-09 06:38 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        if (this.status.isDeleted()) {
```suggestion
        if (isDeleted()) {
```

2024-02-09 06:59 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        if (this.status.isDeleted()) {
해당 내용 수정했습니다

2024-02-09 09:24 UTC, uwoobeat requested changes
soft delete와 hard delete는 DB 상에서의 삭제 구현 방식에 대한 논의이지,
애플리케이션 단에서 특수하게 둘을 구분할 필요가 없고 구분해야 하는 요구사항도 없습니다.
애플리케이션에서 예외 상황을 구별해야 한다면 삭제 했냐 / 안했냐에 대한 문제이지 이게 하드 딜리트인지 소프트 딜리트인지 구별할 필요가 없습니다.

요약하자면 우리 서비스에서 soft delete / hard delete 라는 지식을 가지고 있을 필요가 없습니다. 오히려 도메인 메서드나 예외 코드가 고정되어 버리면 추후 하드 딜리트로 넘어가는 상황에서 대처하기도 어렵습니다.

2024-02-09 09:24 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    public void softDelete() {
```suggestion
    public void withdraw() {
```

의미를 더 잘 드러낼 수 있는 메서드 이름을 써주면 좋을 것 같습니다.

2024-02-09 10:18 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    public void softDelete() {
좋은 지적 감사합니다👍

2024-02-09 11:11 UTC, uwoobeat approved these changes
이 부분만 수정하고 머지하심 될 듯합니다~

2024-02-09 11:11 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
> +    MEMBER_DELETED(HttpStatus.BAD_REQUEST, "탈퇴한 회원입니다.");
409 Conflict가 더 적절해보입니다.

2024-02-09 11:15 UTC, merged