feat: 멤버 도메인의 1차 MVP 기능 제거 및 기존 로직 개선
GDSC-Hongik/gdsc-server pull request #380
Opened 2024-06-12 14:57 UTC by uwoobeat

## 🌱 관련 이슈
- close #374 

## 📌 작업 내용 및 특이사항
> 수정사항이 많으니 꼭 아래 내용 확인 바랍니다!

### 작업배경
- 현재 1차 MVP 정책과 2차 MVP 정책이 혼재되어 있어, 서비스 이해 및 신규 기능 개발에 병목이 되고 있다고 판단했습니다.
- 기존 기능에 대한 하위 호환성을 지키기 위해 `@Deprecated` 등으로 점진적으로 바꾸려고 했지만, 신규 기능 개발 시 이를 인지하지 못하고 1차 정책과 관련된 기능들을 혼용하게 되어 오히려 1차 MVP 기능들과 2차 MVP 기능이 결합되는 결과를 가져오게 된 것 같습니다.
- 이번 PR로 1차 MVP 기능을 완전히 걷어내고, 겸사겸사 기존 로직도 개선했습니다.

### 1. 준회원 승급 과정에 대한 적절한 책임 분담
- 현재 준회원 승급이라는 유즈케이스에 대하여 `AssociateRequirement` VO와 `Member` 엔티티 간의 역할 범위가 모호한 문제가 있어, 이를 개선했습니다.
- 기존에는 verified 되었는지를 확인하기 위해 `RequirementStatus` 필드와 더불어 실제 데이터가 있는 필드가 null이 아닌지를 검사했습니다. 현재는 데이터 필드는 검사하지 않고, 오로지 `RequirementStatus` 필드만을 기준으로 verified 여부를 검사합니다.
    - 즉 `isUnivVerfied() && univEmail != null` 이었다면 현재는 `isUnivVerified()` 만 검사합니다. 

### 2. 준회원 승급 로직 설명
- 준회원 승급은 `advanceToAssociate` 메서드를 통해 이루어집니다. 이는 이벤트 핸들러에 의해 호출되는 메서드입니다.
- 준회원 승급 시 내부적으로 준회원 승급이 가능한지 검증하기 위해 아래 두 검증 메서드를 사용합니다.
    - `validateStatusUpdatable()` -> 공통 상태 변경 여부 검증
    - `validateAssociateAvailable()` -> 준회원 승급 가능 여부 검증
- 이중 `validateAssociateAvailable()` 은 다음 5가지 조건을 확인하여, 조건을 충족하지 않는 경우 예외를 발생시키고, 아니라면 통과합니다. (테스트는 #378 에서 추가할 예정)
    1. 현재 역할이 준회원인지
    2. 재학생 인증 완료했는지
    3. 디스코드 연동 완료했는지
    4. Bevy 연동 완료했는지
    5. 기본정보 입력 완료했는지
 - 여기서 1번 -> 멤버가 가지고 있는 상태이고 2~5번은 `AssociateRequirement` 가 가지고 있는 상태입니다.
 - 따라서, 1번을 validate 하는 로직은 `Member` 엔티티에 위치하고, 2~5번을 검증하는 로직은 `AssociateRequirement` VO에 위치해야 합니다 (이게 핵심입니다)
 - 이를 `associateRequirement.validateAllVerified` 로 묶어서 수행되도록 만들었습니다. 이게 이번 리팩토링의 핵심이라고 이해하시면 됩니다.

### 3. 변경되거나 제거된 로직
- 1차 MVP에서 2차 MVP로 넘어오면서 변동된 정책과 관련된 기능은 모두 삭제되어야 합니다.
- 대표적으로 `grant()` 관련 로직이 있습니다. 이때 해당 로직을 삭제하면서 관련 기능들이 영향받는 경우가 있습니다. 부가적으로 영향받은 부분을 아래에 기재했습니다.
- `isGrantAvailable()`
    - `MemberInfoResponse` 에 `RegistrationStatus` 결정하는 로직에서 사용합니다. 
    - 2차 MVP에서는 필요없으므로 TODO로 주석 남기고, 항상 GRANTED 리턴하도록 했습니다. 
    - 어차피 `MemberInfoStatus` 는 #362 에서 함께 수정될 예정입니다.
- `validateGrantAvailable()`
    - `validateAssociateAvailable()` 로 변경되었습니다. 
- `signup()`
    - `updateBasicMemberInfo()` 로 변경되었습니다.
    - 이에 따라 회원가입 신청 API가 삭제되었습니다.
- `grant()`
    - 회원 승인 API `/grant` 가 삭제되었습니다.
    - `/grantable`, `/granted` API가 삭제되었습니다. 관련 서비스 코드 및 QueryDSL 로직도 삭제되었습니다.
    - '준회원 승급가능 멤버 조회' 라는 기능은 어드민에서 필요하지 않으므로, 관련 테스트 코드를 삭제했습니다.
- `isGranted()` 
    - 디스코드 역할 부여 시 멤버 검증할 때 사용하고 있습니다.
    - 앞으로는 정회원일 때 디스코드 역할 부여하므로 `isRegular()` 로 변경했습니다.
- `MemberRole.USER`
    - 앞으로는 ASSOCIATE, REGULAR만 존재하므로 제거했습니다.
    - 엑셀에서 USER, 즉 승인된 회원 엑셀 시트 생성하는 로직이 있어서 제거했습니다.
- `MemberGrantEvent`
    - 정회원 승급 이벤트로 변경해야 합니다.
    - 현재는 TODO 상태이고 #379 에서 처리해야 합니다 (하실 분...?)
    - 기존에 advanceToAssociate에서 MemberGrantEvent가 발행되고 있어서 삭제해두었습니다.
- `isAtLeastAssociate()`
    - 사용하지 않으므로 제거했습니다.
- `isApplied()`
    - 회원정보 조회 (`/me`) 에서 지원서 제출하지 않으면 예외 발생시키는 목적으로 사용합니다.
    - #362 에서 수정할 예정이므로 해당 예외 로직 제거했습니다.
    - 또한 `OnboardingMemberServiceTest` 의 경우 `/me` 에서의 예외만 검증하는 테스트이므로, 완전히 제거했습니다.

### 그 외 사소한 수정 / 개선사항
- `updateUnivStatus` -> `verifyUniv`
- `verifyInfoStatus` -> `verifyInfo`
- 도메인의 비즈니스 로직이 복잡하여, 섹션별로 분리 (`상태 검증 로직` / `상태 변경 로직` / `데이터 전달 로직`)
- 그 외 사소한 개행 스타일 변경

### 해야 할 일
- 어드민의 경우 현재 준회원 -> 정회원 케이스 어떻게 처리되는지에 대해서 검증이 필요합니다.

## 📝 참고사항
-

## 📚 기타
-

2024-06-12 15:51 UTC, Sangwook02 requested changes
확인했습니다~

2024-06-12 15:51 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberRole.java
24-1 USER들을 24-1 Membership 테이블에 넣어주고 지워야 하지 않나요?

2024-06-12 15:51 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
> +    MEMBER_ALREADY_ASSOCIATE(HttpStatus.CONFLICT, "이미 준회원 역할에 해당하는 회원입니다."),
```suggestion
    MEMBER_ALREADY_ASSOCIATE(HttpStatus.CONFLICT, "이미 준회원인 회원입니다."),
```

2024-06-12 15:51 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/global/util/ExcelUtil.java
> -        createSheet(workbook, GRANTED_MEMBER_SHEET_NAME, USER);
정회원 시트 생성하는 로직이 필요하겠죠?
여유 있을 때 제가 이슈 만들어서 처리하겠습니다~

2024-06-12 15:51 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        associateRequirement.verifyUniv();
```suggestion
        this.associateRequirement.verifyUniv();
```

2024-06-13 01:15 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberRole.java
네 그래서 해당 건 #377에서 다루고 있습니다.
2차 MVP 상용 배포 전에 DB 마이그레이션을 마쳐야 합니다.

2024-06-13 01:25 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        associateRequirement.verifyUniv();
지금 생각해보면 this를 꼭 붙여야 하나? 싶네요.
지역변수와 멤버변수를 명시적으로 구별하기 위해서 사용하는 것은 맞지만,
어차피 IDE 상에서 구별이 된다면 굳이... 싶네요.

++ 찾아보니 김영한 선생님 강의에서도 멤버변수와 지역변수의 변수명이 겹치는 경우가 아니라면 굳이 사용하지 않아도 된다고 하시네요.

> this.nameField = nameParameter; this가 생략되어 있을수도 있다.
IDE가 멤버 변수와 지역 변수를 색상으로 구분해주기 때문에 굳이 사용하지 않아도 된다.

> this.nameField를 보면 this를 생략할 수 있지만, 생략하지 않고 사용해도 된다.
이렇게 this를 사용하면 이 코드가 멤버 변수를 사용한다는 것을 쉽게 확인할 수 있다. 그래서 과거에 이런 스타일을 많이 사용하기도 했다. 
쉽게 이야기해서 this를 강제로 사용해서, 지역 변수(매개변수)와 멤버 변수를 눈에 보이도록 구분하는 것이다. 
하지만 최근에 IDE가 발전하면서 IDE가 멤버 변수와 지역 변수를 색상으로 구분해준다. 다음을 보면 멤버 변수와 지역 변수의 색상이 다른 것을 확인할 수 있다.

[레퍼런스1](https://velog.io/@swsvelog/JAVA-%EA%B9%80%EC%98%81%ED%95%9C%EC%9D%98-%EC%8B%A4%EC%A0%84-%EC%9E%90%EB%B0%94-%EA%B8%B0%EB%B3%B8-1)
[레퍼런스2](https://velog.io/@lgsok00/Java-this)

2024-06-13 01:25 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        associateRequirement.verifyUniv();
괜찮으시면 이 부분 별도 이슈로 분리해서 컨벤션 통일하면 좋을듯 합니다.

2024-06-13 04:55 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        associateRequirement.verifyUniv();
pr 읽다가 좋은 정보 얻어갑니당 
다른분들도 괜찮으시면 이 후부터 this생략하는 것으로 알고 있을까요?

2024-06-13 05:01 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        associateRequirement.verifyUniv();
좋습니다
저도 컨벤션 차원에서 남긴 comment였어요

2024-06-13 05:01 UTC, Sangwook02 approved these changes
lgtm

2024-06-13 05:13 UTC, AlmondBreez3 approved these changes
lgtm

2024-06-13 05:13 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/OnboardingDiscordService.java
> +        if (!member.isRegular()) {
질문입니다
discordRoleAssignable하려면 정회원이어야 하나요?

2024-06-13 09:21 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/OnboardingDiscordService.java
> +        if (!member.isRegular()) {
네 기존 승인 이벤트 기반으로 작동하는 로직이었어서, 승인 -> 정회원 승급으로 대체되었으니 정회원이어야 합니다

2024-06-13 09:25 UTC, merged