feat: 리쿠르팅에 회비와 차수 추가
GDSC-Hongik/gdsc-server pull request #383
Opened 2024-06-13 11:32 UTC by Sangwook02

## 🌱 관련 이슈
- close #369

## 📌 작업 내용 및 특이사항
- 리쿠르팅에 Money(회비)와 RoundType(차수)를 추가했습니다. RoundType은 Enum으로 관리합니다.
- `학년도, 학기, 차수가 모두 중복되는 리쿠르팅`은 생성하지 못하도록 리쿠르팅 생성 Api를 수정했습니다.

## 📝 참고사항
-

## 📚 기타
-

2024-06-13 14:56 UTC, AlmondBreez3 approved these changes
lgtm

2024-06-14 12:14 UTC, uwoobeat requested changes

2024-06-14 12:14 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
> +    private Money fee;
VO라서 `@Embedded` 붙여야 하지 않나요?

2024-06-14 12:14 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
> +            Money fee,
중요한 문제는 아니긴 한데 회차정보가 학기정보 다음에 오고, 회비는 맨 마지막에 오도록 배치하는게 낫지 않나 싶네요

2024-06-14 12:14 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/request/RecruitmentCreateRequest.java
> +        @NotNull(message = "회비는 null이 될 수 없습니다.") @Schema(description = "회비") Money fee,
이거 객체 취급이라서 fee.amount 이런 식으로 요청해야 할 거에요.
그냥 BigDecimal로 받아서 Money 인자로 넘겨주면 어떨까 싶네요

2024-06-14 13:26 UTC, uwoobeat approved these changes
룩스굿투미

2024-06-14 13:26 UTC, merged