feat: 리쿠르팅 수정 API 구현
GDSC-Hongik/gdsc-server pull request #387
Opened 2024-06-15 13:05 UTC by Sangwook02

## 🌱 관련 이슈
- close #335

## 📌 작업 내용 및 특이사항
- 생성 기능과 대체로 비슷하지만 두 가지 다른 점이 있습니다.
  1. 모집 기간이 겹치는 기존 리쿠르팅이 있는지 validate할 때, 자기 자신은 제외하고 검사해야 한다.
  2. 차수가 겹치는 기존 리쿠르팅이 있는지 validate할 때, 자기 자신은 제외하고 검사해야 한다.

## 📝 참고사항
-

## 📚 기타
-

2024-06-15 13:56 UTC, uwoobeat requested changes
`CreateUpdateRequest` 은 어떨까요?
예전에 이렇게 하자고 논의했던 것 같은데 기억이 잘 안나네요.

2024-06-15 14:24 UTC, Sangwook02 commented
> `CreateUpdateRequest` 은 어떨까요? 예전에 이렇게 하자고 논의했던 것 같은데 기억이 잘 안나네요.

중간에 `Or` 있어도 잘 보이지도 않는게 없는게 차라리 짧기라도 해서 나을 것 같네요
수정했습니다~

2024-06-15 14:26 UTC, uwoobeat requested changes

2024-06-15 14:26 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
> +            LocalDateTime startDate,
Period 타입으로 받는건 어떨까요?

2024-06-15 14:26 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
> +            LocalDateTime startDate,
... 라고 했는데 생성할 때도 이렇게 하고 있군요. 해당 이슈에서 전부 Period로 받도록 통일하거나, 별도 이슈로 분리하시거나 편하신대로 작업하시면 될 것 같습니다

2024-06-15 14:26 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/Period.java
> +            throw new CustomException(RECRUITMENT_STARTDATE_ALREADY_PASSED);
Period를 리쿠르팅에 종속적인 VO로 봐야할까요, 아니면 리쿠르팅과 무관한 VO로 보는 것이 좋을까요?
사실 현 시점에서는 둘 중 어느 쪽을 선택하더라도 상관 없을 것 같긴한데, 전자라고 봐도 이 메서드는 올바른 책임을 가진다고 보기 어려울 것 같습니다.

Period는 그냥 시작일과 종료일을 담는 컨테이너이고, 수정이라는 개념도 존재하지 않습니다.
기간을 수정한다는 개념은 리쿠르팅에만 있는 개념이죠.

2024-06-15 14:28 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/Period.java
> +            throw new CustomException(RECRUITMENT_STARTDATE_ALREADY_PASSED);
그러고 보니 값 수정이 아니라 period를 갈아끼우는거니까
리쿠르팅에서 처리하는게 맞겠네요
좋은 지적 감사드립니다~

2024-06-15 14:29 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/common/model/BaseSemesterEntity.java
> +    protected void updateAcademicYear(Integer academicYear) {
그리고 이거 보면서 막 생각난건데 Integer로 받을 거면 연도로 파싱할 수 있는지 검증하는 로직이 있어야 할 것 같습니다.
아니면 `java.time.Year` 같은 걸 쓸 수 있지 않을까요?
이 PR과 관련없긴 한데 별도 이슈로 분리해보면 좋을 것 같습니다

2024-06-15 14:29 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
> +            LocalDateTime startDate,
코드 읽기에는 Period로 받도록 하는게 좋을 것 같기는 해요
이 부분은 별도 이슈로 처리할게요!

2024-06-15 14:54 UTC, uwoobeat requested changes

2024-06-15 14:54 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
> +    private void validatePeriodOverlap(
자기 자신은 제외해야 하는 이유가 뭔가요?

2024-06-15 14:54 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
> +        List<Recruitment> recruitments =
마지막 recruitmentId도 파라미터명을 더 명료하게 사용하면 어떨까 싶습니다.

2024-06-15 14:57 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
> +    private void validatePeriodOverlap(
자기 자신의 기간은 수정에 성공하는 순간 사라지기 때문에 무의미합니다.
근데 만약 이걸 제외하지 않는다면 `3/1~3/3`의 기간을 `3/1~3/2`로 바꾸고자 할때 예외가 발생하게 되므로 제외해야 해요

2024-06-15 15:00 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
> +        List<Recruitment> recruitments =
바꾸는 김에 위에 있는 유사한 케이스도 같이 수정했습니다~

2024-06-15 17:14 UTC, uwoobeat approved these changes
아래 부분만 수정해주세요
미리 어푸날립니다

2024-06-15 17:14 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
> +        List<Recruitment> recruitments =
메서드 이름도 비슷하게 수정해주세요.
`validateRoundOverlapWithoutCurrentRecruitment(...)`

주석으로 왜 현재 리쿠르팅을 제외하는지도 간단하게 적어주세요.

2024-06-16 04:06 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
> +                .ifPresent(recruitment -> {
그렇군요👍👍

2024-06-16 05:51 UTC, AlmondBreez3 approved these changes
lgtm

2024-06-16 06:22 UTC, merged