refactor: 멤버 등급 정회원 승급 및 멤버십 상태 VERIFIED 변경 로직
GDSC-Hongik/gdsc-server pull request #388
Opened 2024-06-15 13:40 UTC by AlmondBreez3

## 🌱 관련 이슈
- close #379 

## 📌 작업 내용 및 특이사항
- TODO grant -> regular바꾸어두었습니다
- MembershipService의 advanceToRegular보시면 Membership PENDING -> VERIFIED 랑 Member ASSOCIATE -> REGULAR
이 두가지가 들어가있는데 회비 납부 할때 저 두 로직이 다 필요하다고 생각해서 묶어놨는데 따로 분리해서 메서드를 구성하는게 맞을지 아니면 현재 구현된 구성으로 가는게 맞는지 의견 여쭈어봅니다..!

## 📝 참고사항
-

## 📚 기타
-

2024-06-15 14:52 UTC, Sangwook02 requested changes
확인했습니다

2024-06-15 14:52 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    }
regular가 되기 위한 조건을 모두 만족했는지 확인해야 하지 않나요?
line 130 참고하시면 좋을 듯 합니다~

2024-06-15 14:52 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> +        void 멤버십_상태와_멤버_역할_승급_성공한다() {
멤버십 상태보다 구체적으로 적어주세요

2024-06-15 14:52 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> +        void 멤버십_상태와_멤버_역할_승급_성공한다() {
line 144도 같이 부탁드립니다~

2024-06-15 14:52 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberAdvanceToRegularEvent.java
> +public record MemberAdvanceToRegularEvent(String discordUsername, String nickname) {}
핸들러를 살펴보니 nickname은 사용하지 않는 것 같습니다
record가 닉네임도 가지고 있어야 하는 이유가 있나요?

2024-06-15 14:52 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/listener/MemberAdvanceToRegularEventListener.java
> +@Slf4j
```suggestion
```

2024-06-15 14:52 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +    }
Member 클래스에 남긴 리뷰 확인하시면 이 부분 정리 가능할 것 같습니다

2024-06-15 15:48 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberAdvanceToRegularEvent.java
> +public record MemberAdvanceToRegularEvent(String discordUsername, String nickname) {}
이거 재현님이 만들어두신거 이름만 바꾼거라서 저 부분에 대해선 카톡이나 내일 회의때 물어보겠습니다

2024-06-15 15:55 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    }
associate에서 이미 확인하는걸 regular로 승급할 때 또 하는게 중복 느낌 들어서 안한건데
알겠습니다!

2024-06-15 15:56 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +    }
이건 근데 멤버십이랑 멤버라서 좀 다르지 않나용?

2024-06-15 16:04 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    }
associate에서는 준회원 승급 조건을 확인하고 있고,
여기서는 정회원 승급 조건을 확인해야 합니다.
중복되는 부분이 없지 않나요?

2024-06-15 17:40 UTC, uwoobeat requested changes

2024-06-15 17:40 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        Optional.of(currentMembership)
멤버십을 쿼리할 때 존재하지 않는 경우 예외를 던지도록 했는데, 아래에서 `Optional` 로 한번 더 싸서 로직을 끌고가는 이유가 있나요?

2024-06-15 17:40 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        currentMember.advanceToRegular();
멤버십 서비스인데, 멤버에 대한 로직을 처리하고 있는게 어색한 것 같습니다.

2024-06-15 17:40 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberAdvanceToRegularEvent.java
> +public record MemberAdvanceToRegularEvent(String discordUsername, String nickname) {}
이거 원래 grant 할 때 유저네임 / 디스코드 닉네임 싱크 맞춰주려고 보낸건데, 지금은 해당 로직 없기 때문에 디스코드 유저네임으로만 이벤트 발행해도 괜찮습니다.

2024-06-15 17:40 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    }
준회원 승급조건은 멤버 도메인에서 관리하는 정보이지만, 정회원 승급조건은 멤버십에서 관리하고 있습니다.
실제로 멤버십 엔티티에 `RegularRequirement` VO가 존재하는 이유이기도 하고요.

따라서 멤버 도메인에서 검증할 수 있는 부분은 자신의 역할이 정회원인데 정회원 승급 요청을 받는 것인지밖에 없습니다.

2024-06-15 17:40 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        registerEvent(new MemberAdvanceToRegularEvent(discordUsername, nickname));
개행 컨벤션 체크해주세요

2024-06-15 17:40 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    public void advanceToRegular() {
정회원 승급에 대해서도 주석 적어주세요

2024-06-15 17:40 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> +        void 멤버십_상태와_멤버_역할_승급_성공한다() {
정회원 승급은 멤버십 상태가 유효할 때 이벤트 발행되어 처리되는 것 아닌가요?
정회원 승급이 원인이 되어 멤버십 상태가 변경되는 케이스가 있나요?

2024-06-16 02:31 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        currentMember.advanceToRegular();
회비 결제 ->멤버십 verified 갱신 + 멤버 regular로 갱신 이 두가지가 충족되야 하는 것으로 알고 있는데 일단 각 멤버, 멤버십 서비스에 각각에 대한 메소드를 만들어 두는게 맞을까요?

2024-06-16 02:32 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        Optional.of(currentMembership)
최대한 한줄로 줄이고 싶어서 optional 활용해서 람다식 쓴건데 이미 예외 던지도록 해두었으면 없어도 충분하겠네용!

2024-06-16 04:18 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    }
아 그렇네요
분리했다는 사실을 잊고 있었어요
그럼 여기에서 확인할 건 아닌 것 같네요
이 comment는 무시하셔도 될 것 같습니다~

2024-06-16 05:09 UTC, uwoobeat requested changes

2024-06-16 05:09 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        Optional.of(currentMembership)
최대한 한줄로 줄이고 싶은 이유가 뭔가요?
아마 람다식의 표현력 상의 장점을 살리고 싶다는 의도로 이해했는데 맞을까요?
Optional에 람다식을 쓴다고 해서 항상 표현력이 좋아지는 것은 아닙니다.

작성하신 로직의 경우 Optional 없이 작성한다면 아래와 같이 간단하게 나타낼 수 있습니다.

```java
if (!currentMembership.isAdvanceToRegularAvailable()) {
    throw new CustomException(MEMBERSHIP_ALREADY_VERIFIED);
}

currentMember.advanceToRegular();
```

`Optional.of` 를 사용해야 하는 상황을 찾아보시면 좋을듯 핣니다.

2024-06-16 05:09 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        Optional.of(currentMembership)
추가로, 응용 레이어에 위와 같은 if 조건 throw 같은 validation 로직이 들어가있는 것도 좋은 사례는 아닙니다.
해당 validation은 멤버십 내부에서 public으로 노출된 validateAdvanceToRegularAvailable() 같이 처리하면 어떤 예외가 발생하는지도 캡슐화할 수 있습니다.

2024-06-16 05:58 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        Optional.of(currentMembership)
네네 그 장점을 살리고 싶었습니다! Optional에 대해 잘 알지 못하고 사용해서 저렇게 했던것같네요..ㅋㅋㅋ저 부분은 다시 반영해주신대로 고치겠습니다

2024-06-16 06:34 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +                .filter(Membership::isAdvanceToRegularAvailable)
엇 근데 isAdvanceToRegularAvailable
이건 기존에 재현님이 멤버십의 isPaymentVerified를 검증 해둔 함수인데 여기서 정회원 승급 조건 모두 충족하는지에 대한 건 확인을 못하지않나용?

2024-06-16 14:06 UTC, Sangwook02 requested changes

2024-06-16 14:06 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    }
line 107 쯤에 검증 로직들 모여있습니다.
옮겨주세요~

2024-06-16 14:06 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/MemberAdvanceToRegularEventHandler.java
> +                .findById(Long.valueOf(memberId))
박싱 불필요 하지 않나요?

2024-06-16 14:06 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +    }
line 107쯤에 검증 로직 모여있습니다!
옮겨주세요~

2024-06-16 14:09 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        if (this.role != ASSOCIATE) {
```suggestion
        if (!role.equals(ASSOCIATE)) {
```

2024-06-16 14:11 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/MemberAdvanceToRegularEventHandler.java
> +                .findById(Long.valueOf(memberId))
저러면 오류가 나서..ㅜㅜ Member라고 똑같은 이름의 객체가 있으면 안되나봐요..그래서 이벤트 분리 어떨까 했습니다!

2024-06-16 17:04 UTC, uwoobeat requested changes

2024-06-16 17:04 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/MemberAdvanceToRegularEventHandler.java
> +public class MemberAdvanceToRegularEventHandler implements SpringEventHandler {
`SpringEventHandler`, `DiscordEventHandler` 등은 디스코드 로직 처리 전용입니다.
만약 DB 로직을 처리해야 한다면 별도의 이벤트 리스너를 만들어서 처리하게 만들어야 합니다.

즉 하나의 이벤트에 대해 디스코드 리스너 + 핸들러 -> 서버에 역할 부여, 일반 리스너 + 핸들러 -> 트랜잭션 처리 이렇게 두 가지로 처리해야 합니다.

2024-06-16 22:38 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/MemberAdvanceToRegularEventHandler.java
> +public class MemberAdvanceToRegularEventHandler implements SpringEventHandler {
넵! 저도 그 필요성을 느껴서 advanceToRegular관련 이벤트 따로 기존의 discordEvent따로 두는게 맞다고 판단했습니다! 그렇게 그럼 수정하는 방향으로 가곘습니다!

2024-06-17 03:49 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/MemberAdvanceToRegularEventHandler.java
> +                .findById(Long.valueOf(memberId))
`Long.valueOf` 이 부분 말씀드린겁니다!

2024-06-17 03:56 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/MemberAdvanceToRegularEventHandler.java
> +                .findById(Long.valueOf(memberId))
아 그러네요 알겠습니다~!

2024-06-17 06:12 UTC, seulgi99 requested changes

2024-06-17 06:12 UTC, seulgi99 commented on src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
> +    }
```suggestion
    public void validateAdvanceRequirement() {
        if (isAdvanceRequirementAllSatisfied()) {
            throw new CustomException(MEMBERSHIP_ALREADY_VERIFIED);
        }
    }
```

이런식으로 줄이면 더 알아보기 좋을 것 같습니다

2024-06-17 10:25 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
> +    }
코드들이 저런 형식으루 많이 되어있어서 맞춰서 했습니답!

2024-06-17 14:37 UTC, uwoobeat requested changes

2024-06-17 14:37 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
> +    public boolean isAdvanceRequirementAllSatisfied() {
AdvanceRequirement라는 대상은 없지 않나요?

2024-06-17 14:37 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
> +    }
슬기님이 제안해주신 버전이 더 좋아보입니다.
이런 식으로 되어있지 않은 패턴이 있나요?
만약 그런 케이스가 있으면 리팩토링하거나 TODO 주석 남겨주시면 좋을듯 합니다

2024-06-17 14:37 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> +        void 멤버십_상태_승급_성공한다() {
'무엇을 하면' 멤버십 상태 승급 성공하는지가 나타나있지 않습니다.
그리고 멤버십은 상태 승급이라는 개념이 없습니다. 정회원 승급 조건 충족이라는 개념만 있습니다.
승급에 해당하는 advance는 멤버에서만 사용되어야 합니다.

2024-06-17 21:21 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
> +    public boolean isAdvanceRequirementAllSatisfied() {
RegularRequirement로 바꾸겠습니다

2024-06-17 21:24 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
> +    }
validate 검증 함수에 몇개 되어있는 것 같은데 주석 처리 남기고 커밋하겠습니다

2024-06-18 11:08 UTC, Sangwook02 requested changes
리뷰 남겼습니다

2024-06-18 11:08 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
> +    }
line 73에 검증로직 모여있습니다 옮겨주세요~

2024-06-18 11:08 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/application/handler/MemberRegularEventHandler.java
> +            log.info("success");
로그를 success 라고만 남기면 어떤 맥락에서 성공한건지 알 수 없습니다.
맥락에 대한 정보를 포함하던지 제거하는게 좋을 것 같습니다.

2024-06-18 11:41 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
멤버십 상태가 따로 있어서 memberRole은 아닌것 같습니다!!  단지 실패하는 부분멤버 역할은 memberRole로 바꿔놓겠습니다

2024-06-18 11:42 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/application/handler/MemberRegularEventHandler.java
> +            log.info("success");
넵

2024-06-18 11:45 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
잘 이해가 안 되는데 멤버십 상태가 뭔가요?
코드만 봤을 때는 Regular requirement를 멤버십 상태라고 하신 것 같은데, 그렇다면 멤버십 상태보다 정회원 승급조건 같은 용어가 적절하지 않나요?

2024-06-18 12:00 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
흠 그러네요
멤버십 상태가 VERIFIED가 됐다 이거를 생각한건데 
흐으음..

2024-06-18 13:19 UTC, uwoobeat requested changes

2024-06-18 13:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/listener/DelegateMemberEventListener.java
> +    public void handleMemberAdvanceToRegularEvent(MemberRegularEvent event) {
핸들러 메서드와 이벤트의 이름이 다릅니다.
이벤트 이름을 바꾸거나 핸들러 이름을 바꿔야 합니다.

2024-06-18 13:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +    public void advanceToVerified(Long membershipId) {
verified로 승급한다는 개념은 없습니다.

2024-06-18 13:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +    public void advanceToVerified(Long membershipId) {
메서드 이름만 봤을 때 어떤 로직을 수행하는지 예상이 가지 않는 것 같습니다.

2024-06-18 13:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
>                  .ifPresent(membership -> {
indentation 최소화해주세요. 로직 가독성이 너무 안좋습니다.

2024-06-18 13:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        currentMembership.validateAdvanceRequirement();
AdvanceRequirement라는 대상은 없습니다.

2024-06-18 13:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +        currentMembership.verifyPaymentStatus();
verfiy 내부에서 validation을 수행하는 편이 낫지 않나요?

2024-06-18 13:19 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> +    class 회비_납부시 {
현재는 정회원 승급조건 == 회비 납부여부이지만, 앞으로는 추가될 가능성이 있습니다.
준회원 승급조건이 여러 개의 조건으로 구성된 것처럼 정회원도 그렇게 될 가능성이 높습니다.
따라서 회비 납부의 컨텍스트와 정회원 승급조건 충족의 컨텍스트를 분리해야 합니다.

지금 테스트 로직을 보면 정회원 승급조건을 회비 납부여부와 동일시하는 부분이 많습니다.
이러한 부분도 수정되어야 합니다.

2024-06-18 13:19 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> +        void 정회원_승급조건_충족_됐다면_성공한다() {
정회원 승급조건이 충족되었다는 것은 이미 회비 납부처리가 완료된 것 아닌가요?
선후관계가 이상합니다.

2024-06-18 13:20 UTC, Sangwook02 requested changes

2024-06-18 13:20 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +            throw new CustomException(MEMBER_NOT_GRANTED);
우리 서비스에 이제 grant라는 개념이 없지 않나요? 수정 필요해보입니다!

2024-06-18 13:20 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
> +        this.role = REGULAR;
```suggestion
        role = REGULAR;
```

2024-06-18 13:20 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/application/handler/MemberRegularEventHandler.java
> +            log.info("{}", e.getErrorCode());
에러이므로 log.error를 사용하는 것이 적절할 것 같습니다.
++ GlobalExceptionHandler 클래스를 참고해서 로그 내용 수정해주시면 좋을 것 같습니다.

2024-06-18 13:20 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/listener/DelegateMemberEventListener.java
> +    public void handleMemberAdvanceToRegularEvent(MemberRegularEvent event) {
하나의 이벤트에 2개의 메서드로 분리하는거라고 생각해서 저렇게 했는데 혹시 제가 잘못이해한게 있나요?

2024-06-18 13:21 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
>                  .ifPresent(membership -> {
저부분은 상욱님이 한거라서 어떤 부분을 처리하신지 여쭈어바야할것같습니다

2024-06-18 13:23 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
>                  .ifPresent(membership -> {
style 관련 사항은 수정해주셔도 됩니다!

2024-06-18 13:27 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/listener/DelegateMemberEventListener.java
> +    public void handleMemberAdvanceToRegularEvent(MemberRegularEvent event) {
아 넵 죄송해요 확인 못했네요..

2024-06-18 13:30 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/application/handler/MemberRegularEventHandler.java
> +            log.info("{}", e.getErrorCode());
넵 근데 그럼 상욱님 그럼 저렇게 하면 error가 터지는 게 아니라 에러 메세지를 좀더 명시적으로 보여주는건가요?

2024-06-18 13:35 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/application/handler/MemberRegularEventHandler.java
> +            log.info("{}", e.getErrorCode());
> 에러이므로 log.error를 사용하는 것이 적절할 것 같습니다. 

log level로 구글링 해보시면 info와 error 이해하기 좋으실 것 같습니다

> ++ GlobalExceptionHandler 클래스를 참고해서 로그 내용 수정해주시면 좋을 것 같습니다.

메시지 포맷을 통일하는게 좋을 것 같아서 남긴 리뷰입니다

2024-06-18 13:44 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
> +    public void advanceToVerified(Long membershipId) {
verifyPaymentStatus로 바꾸었습니다 준회원 로직 비슷하게 생각하니까 감이 잡히는 것 같습니다

2024-06-18 14:47 UTC, uwoobeat requested changes

2024-06-18 14:47 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/application/handler/MemberRegularEventHandler.java
> +            log.info("{}", e.getErrorCode());
info가 적절할 것 같습니다.
advanceToRegular의 경우 verify가 발생했을 때마다 이벤트를 통해 항상 시도됩니다.
이때 try-catch로 감싼 이유는 exception 발생으로 인해 verify가 수행되는 command가 rollback되는 것을 막기 위함입니다.
즉 승급조건이 4개라면 1,2,3회차에는 항상 advanceToRegular가 발생하고 마지막에 성공합니다.

이는 예외적인 문제가 아니고 의도된 부분이기 때문에 error도 warn도 아닙니다. 따라서 info를 사용하는 것이 적절합니다.

2024-06-19 16:39 UTC, uwoobeat approved these changes
코멘트 남긴 부분은 기능에 큰 영향있는 부분은 아니라서 먼저 승인해두겠습니다
수고하셨습니다~

2024-06-19 16:39 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/DelegateMemberDiscordEventHandler.java
> +public class DelegateMemberDiscordEventHandler implements SpringEventHandler {
기존과 동일하게 `MemberRegularEventHandler` 가 되어야 하지 않나요?
변경된 이유가 궁금합니다.

2024-06-19 22:47 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/DelegateMemberDiscordEventHandler.java
> +public class DelegateMemberDiscordEventHandler implements SpringEventHandler {
정회원 승급 handler 따로 둬야 한다고 판단해서 discord랑 memberregulareventhandler랑 구분했습니다!

2024-06-20 00:48 UTC, Sangwook02 requested changes

2024-06-20 00:48 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> -                    .hasMessage(MEMBERSHIP_ALREADY_VERIFIED.getMessage());
`MEMBERSHIP_ALREADY_VERIFIED`와 `MEMBERSHIP_ALREADY_APPLIED`는 같지 않습니다.
전자는 이미 Membership을 발급을 받은 것이고 후자는 db에 생성만 해둔 상태입니다.

저는 아래와 같은 상황들을 고려해서 둘을 분리했습니다.

- 1차 리쿠르팅 때 A라는 회원이 멤버십을 생성 하고 정회원 승인 조건을 만족시킨 상황을 가정해보면,
2차 때 새로 멤버십을 생성하고자 할 때 `MEMBERSHIP_ALREADY_VERIFIED`로 안내해주는게 맞습니다.

- 1차 리쿠르팅 때 A라는 회원이 멤버십을 생성 하고 정회원 승인 조건을 아직 만족시키지 않은 상황을 가정해보면,
1차 때 새로 멤버십을 생성하고자 할 때 `MEMBERSHIP_ALREADY_APPLIED`로 안내해주는게 맞습니다.

한비님께서 이 둘을 하나로 합쳐도 되겠다고 판단하셨다면 그 이유가 궁금하고, 합치게 된다면 기존에 `MEMBERSHIP_ALREADY_VERIFIED`를 위해 존재했던 본 test는 수정이 아니라 제거해야 합니다.

2024-06-20 00:48 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> -                    .hasMessage(MEMBERSHIP_ALREADY_VERIFIED.getMessage());
++ 근데 이 부분이 현재 이슈랑 관련이 있나요...?

2024-06-20 00:52 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> -                    .hasMessage(MEMBERSHIP_ALREADY_VERIFIED.getMessage());
아니라서...다른 이슈 파서 하겠다는 것이었습니다!! 
남겨주신 코멘트 참고해서 반영하겠습니다...!!

2024-06-20 00:57 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> -                    .hasMessage(MEMBERSHIP_ALREADY_VERIFIED.getMessage());
네 
근데 이슈를 따로 파신다고 했는데 수정이 되어있길래 추가로 리뷰남긴거였어요

2024-06-20 01:00 UTC, AlmondBreez3 commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> -                    .hasMessage(MEMBERSHIP_ALREADY_VERIFIED.getMessage());
아아 수정 후 이슈 파서 다시 해야겠다 했서 리뷰 요청했는데
지금 보니까 어차피 컨플릭트 나니까 오늘 중으로 다시 원래대로 돌려놓고 
pr부탁드리겠습니다~

2024-06-20 01:08 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
> -                    .hasMessage(MEMBERSHIP_ALREADY_VERIFIED.getMessage());
한 가지 더 궁금한 점이 생겼는데요,,
`fix: indent수정`이라는 커밋을 살펴보면 정작 indentation은 수정되어있지않고
```
if (membership.isRegularRequirementAllSatisfied()) {
                        throw new CustomException(MEMBERSHIP_ALREADY_VERIFIED);
                    }
```
이 부분만 제거가 되어있습니다.

이유를 알 수 있을까요?

2024-06-20 16:09 UTC, Sangwook02 approved these changes
lgtm

2024-06-21 11:59 UTC, seulgi99 commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/listener/DelegateMemberDiscordEventListener.java
> +    @TransactionalEventListener(classes = MemberRegularEvent.class)
여기도 phase = TransactionPhase.BEFORE_COMMIT 조건을 달아줘야하지않을까요? 

다른 이벤트들 처럼 해당 핸들러에서 에러나면 기존 변경사항들도 rollback시켜줘야 하지않을까요?

2024-06-21 12:02 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/discord/application/listener/DelegateMemberDiscordEventListener.java
> +    @TransactionalEventListener(classes = MemberRegularEvent.class)
엇 근데 저건 디비에 저장되거나 그런게 아니라서 상관없지않나욥??

2024-06-22 12:24 UTC, merged