feat: 정회원 일괄 강등 API 구현
GDSC-Hongik/gdsc-server pull request #393
Opened 2024-06-18 10:26 UTC by Sangwook02

## 🌱 관련 이슈
- close #347

## 📌 작업 내용 및 특이사항
- 멤버 서비스에서 리쿠르팅에 대하여 아래의 두 가지를 검증하기 위한 이벤트를 발행합니다. 
    1. 해당 학기에 리쿠르팅이 존재 하는가
    2. 해당 학기의 리쿠르팅이 모두 시작하기 전인가
- 발행된 이벤트의 핸들러에서는 AdminRecruitmentService에 검증을 요청합니다. 검증이 Exception 없이 이루어진다면, AdminMemberService로 돌아와 정회원 모두를 준회원으로 강등합니다.
  
## 📝 참고사항
-

## 📚 기타
-

2024-06-18 12:02 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberDemoteRequest.java
> +public record MemberDemoteRequest(Integer academicYear, SemesterType semesterType) {}
Request Dto로 이벤트를 발행해도 되겠지만,
네이밍도 그렇고 이 둘은 명확하게 구분, 분리 해주는게 좋을 것 같아서 이렇게 구현했습니다

2024-06-18 12:04 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/application/handler/MemberDemoteValidationEventHandler.java
> +    public void validateRegularMembersDemoteAvailable(MemberDemoteValidationEvent memberDemoteValidationEvent) {
`MemberDemoteValidationEventListener`가 없기 때문에 `EventListener` 어노테이션을 달아주지 않으면 핸들러가 실행되지 않습니다.

2024-06-18 12:26 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberDemoteRequest.java
> +public record MemberDemoteRequest(Integer academicYear, SemesterType semesterType) {}
앗 넵 알겠숩니당

2024-06-18 12:27 UTC, AlmondBreez3 commented on src/main/java/com/gdschongik/gdsc/domain/recruitment/application/handler/MemberDemoteValidationEventHandler.java
> +    public void validateRegularMembersDemoteAvailable(MemberDemoteValidationEvent memberDemoteValidationEvent) {
앗 그렇군용 감사합니다~~

2024-06-18 12:53 UTC, AlmondBreez3 approved these changes
lgtm

2024-06-18 13:49 UTC, uwoobeat requested changes

2024-06-18 13:49 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
> +    @Operation(summary = "정회원 일괄 강등", description = "모든 정회원을 준회원으로 일괄 강등합니다.")
```suggestion
    @Operation(summary = "정회원 일괄 강등", description = "모든 정회원을 준회원으로 일괄 강등합니다. 리쿠르팅 시작 전에 사용합니다.")
```

2024-06-18 13:49 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
> +        applicationEventPublisher.publishEvent(
서비스 조회 대신 이벤트로 처리하신 이유가 있나요?

이벤트는 발행자가 후속조치를 신경쓰지 않아도 될 때 사용합니다. 만약 발행된 이벤트의 구독자가 리턴하는 값을 필요로 하는 등 동기적인 처리가 필요하다면 서비스를 사용하여 처리하는 것이 좋습니다.

2024-06-18 14:17 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
> +        applicationEventPublisher.publishEvent(
recruitment에 대한 조회 및 검증은 `AdminRecruitmentService`에서 하는게 적절할 것 같아서 검증 로직을 `AdminRecruitmentService`에 뒀습니다.

근데 이걸 서비스 -> 서비스 호출하는 것보다 이벤트로 처리하는게 덜 어색하다고 생각했습니다.

멤버 서비스에서 바로 리쿠르팅 서비스를 호출하는 게 좋을까요?

2024-06-18 16:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
> +        applicationEventPublisher.publishEvent(
서비스에서 서비스 호출해도 괜찮습니다.
검색해보시면 김영한 강의 QnA 레퍼런스인가에 있을 거에요.

2024-06-18 16:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
> +        applicationEventPublisher.publishEvent(
앞서 말한 것처럼 동기적인 작업이 필요할 때는 이벤트를 사용하지 않습니다.

2024-06-19 01:23 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
> +        applicationEventPublisher.publishEvent(
[이거](https://www.inflearn.com/questions/111740/%EC%84%9C%EB%B9%84%EC%8A%A4-%EC%95%88%EC%97%90%EC%84%9C-%EB%8B%A4%EB%A5%B8-%EC%84%9C%EB%B9%84%EC%8A%A4-%ED%98%B8%EC%B6%9C%EC%97%90-%EA%B4%80%ED%95%98%EC%97%AC) 말씀하시는 것 같네요..
반영하겠습니다~

2024-06-19 01:39 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
> +        applicationEventPublisher.publishEvent(
생각난김에 로그도 같이 추가했습니다

2024-06-19 01:57 UTC, seulgi99 approved these changes
확인했습니다!

2024-06-19 16:43 UTC, uwoobeat approved these changes
lgtm

2024-06-19 16:44 UTC, merged