feat: 쿠폰 API 구현
GDSC-Hongik/gdsc-server pull request #397
Opened 2024-06-18 17:22 UTC by uwoobeat

## 🌱 관련 이슈
- close #357

## 📌 작업 내용 및 특이사항
- 쿠폰 조회 / 생성, 쿠폰 발급 / 회수 API 구현
- 쿠폰 수정은 제외
- 쿠폰 생성 정책 -> 할인금액 양수여야 함
- 발급쿠폰 사용 정책 -> 사용여부, 회수여부 검증. 단 현재는 발급쿠폰 사용 유즈케이스 없음 (추후 결제 기능에서 사용)
- 발급쿠폰 회수 정책 -> 사용여부 검증. 회수여부는 검증 X이고 여러 번 회수 요청 보내더라도 멱등함
- `DatabaseCleaner` 에서 두 단어 조합(`Issued` + `Coupon`)인 경우 작동 안하는 오류 있어서 함께 수정 ***

## 📝 참고사항
- 커맨드 요청인 경우 로그 남기도록 했음
- 정책에 대한 테스트 작성

## 📚 기타
-

2024-06-19 01:20 UTC, Sangwook02 requested changes
확인했습니다~

2024-06-19 01:20 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/coupon/api/AdminCouponController.java
> +    public ResponseEntity<Void> deleteIssuedCoupon(@PathVariable Long issuedCouponId) {
다른 곳에서는 모두 revoke를 사용했는데 여기에만 delete 사용하신 이유가 있나요?
```suggestion
    public ResponseEntity<Void> revokeIssuedCoupon(@PathVariable Long issuedCouponId) {
```

2024-06-19 01:20 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/coupon/api/AdminCouponController.java
Coupon을 생성하고 이를 멤버들에게 일대다로 발급한다는 내부 구현을 모르는 기획팀이나 프론트팀 입장에서,
`쿠폰 생성`과 `쿠폰 발급`이 헷갈릴 것 같습니다. description을 조금 보완하면 좋을 것 같아요~

2024-06-19 01:20 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/coupon/application/CouponService.java
> +        log.info("[CouponService] 쿠폰 회수: issuedCouponId={}", issuedCouponId);
이미 회수된 쿠폰을 다시 회수하려고 하는 경우,
같은 log가 두 번 찍혀버리지 않나요?

2024-06-19 01:20 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/coupon/application/CouponService.java
> +        Member currentMember = memberUtil.getCurrentMember();
이 메서드를 어드민이 호출하는걸로 아는데, 그럼 쿠폰 발급이 어드민 본인에게 이루어지는거 아닌가요?
다른 멤버에게 발급하려면 dto로 발급 대상자를 받아야 할 것 같습니다!

2024-06-19 02:07 UTC, seulgi99 reviewed
코멘트 남겼습니다~~

2024-06-19 02:07 UTC, seulgi99 commented on src/main/java/com/gdschongik/gdsc/domain/coupon/domain/Coupon.java
Coupon에 사용기간, IssuedCoupon에 만료기간(createAt + coupon의 사용기간)은 필요하지 않은건가요? 예를들어 2024-2학기에 발급받은 쿠폰을 2025-1학기에도 쓸수있고, 2학기에도 쓸수있을거같아서요!
기간에 대한 정책은 없는건가요?

2024-06-19 02:07 UTC, seulgi99 commented on src/main/java/com/gdschongik/gdsc/domain/coupon/dto/request/CouponIssueRequest.java
request에 발행할 멤버id(or List)를 넣어주시는게 좋을거같습니다!

2024-06-19 16:46 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/coupon/api/AdminCouponController.java
> +    public ResponseEntity<Void> deleteIssuedCoupon(@PathVariable Long issuedCouponId) {
코파일럿이 일을 똑바로 안하네요 수정해둘게용

2024-06-19 17:09 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/coupon/api/AdminCouponController.java
수정완

2024-06-19 17:10 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/coupon/application/CouponService.java
> +        log.info("[CouponService] 쿠폰 회수: issuedCouponId={}", issuedCouponId);
넹 생각해보니 회수가 멱등할 필요는 없겠네요

2024-06-19 17:15 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/coupon/application/CouponService.java
> +        Member currentMember = memberUtil.getCurrentMember();
레전드급실수발생

2024-06-19 17:17 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/coupon/domain/Coupon.java
네 만료기간에 대한 점을 고려 안한 것은 아닌데, 당장 정책적으로 꼭 필요하다는 느낌은 아니라서 이번 MVP에서는 제외했습니다
추후 쿠폰 디벨롭 하면서 (ex. 스터디 수료 여부에 따른 발급) 넣을 생각입니다~

2024-06-19 22:48 UTC, AlmondBreez3 approved these changes
lgtm

2024-06-20 00:30 UTC, Sangwook02 approved these changes
controller 메서드명 하나만 수정부탁드릴게요
미리 어푸드림

2024-06-20 00:30 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/coupon/api/AdminCouponController.java
> +    public ResponseEntity<Void> deleteIssuedCoupon(@PathVariable Long issuedCouponId) {
이 부분 깜빡하신 것 같네요

2024-06-20 11:04 UTC, merged