refactor: 과제 엔티티 필드 이름 수정
GDSC-Hongik/gdsc-server pull request #416
Opened 2024-06-25 14:22 UTC by AlmondBreez3

## 🌱 관련 이슈
- close #415 

## 📌 작업 내용 및 특이사항
- 추후 작업에 필요한 엔티티 안에 필드명 수정했습니다~

## 📝 참고사항
-

## 📚 기타
-

2024-06-25 14:25 UTC, Sangwook02 approved these changes
lgtm

2024-06-26 05:30 UTC, seulgi99 requested changes
이거를 isCancelled로 두려고했는데
결국 Assignment와 Session이 StudyDetail이라는 같은 테이블에 들어가서
둘에게 모두 존재하는 휴강여부, 제목, 난이도를 똑같이 title, isCancelled, difficulty로 둘순 없겠더라구요 (db컬럼중복)
그래서 구분해뒀습니다!

그래서 그럼 클래스의 필드값은 title, isCancelled, difficulty이렇게 두되
각각

@Column(name = "assignmentTitle")
https://github.com/column(name = "isAssignmentCancelled")
https://github.com/column(name = "assignmentDifficulty")
이렇게 지정하는건 어떨까요?

2024-06-26 11:15 UTC, AlmondBreez3 commented
> 이거를 isCancelled로 두려고했는데 결국 Assignment와 Session이 StudyDetail이라는 같은 테이블에 들어가서 둘에게 모두 존재하는 휴강여부, 제목, 난이도를 똑같이 title, isCancelled, difficulty로 둘순 없겠더라구요 (db컬럼중복) 그래서 구분해뒀습니다!
> 
> 그래서 그럼 클래스의 필드값은 title, isCancelled, difficulty이렇게 두되 각각
> 
> @column(name = "assignmentTitle") @column(name = "isAssignmentCancelled") @column(name = "assignmentDifficulty") 이렇게 지정하는건 어떨까요?

네네 좋습니다

2024-06-26 11:55 UTC, uwoobeat reviewed
중복 컬럼명의 경우 `@AttributeOverride` 를 쓰면 됩니다

2024-06-26 12:27 UTC, seulgi99 approved these changes
좋습니다~

2024-06-26 12:47 UTC, uwoobeat approved these changes
lgtm

수정할 부분이 있긴한데 별도 이슈로 치겠습니다

2024-06-26 12:47 UTC, merged