feat: BaseTimeEntity에 생성자와 수정자 추가
GDSC-Hongik/gdsc-server pull request #420
Opened 2024-06-26 13:02 UTC by Sangwook02

## 🌱 관련 이슈
- close #331

## 📌 작업 내용 및 특이사항
- BaseTimeEntity에 `createdBy`와 `updatedBy`를 추가했습니다.
 `@EnableJpaAuditing`만 달아주면 되는 날짜와 달리 AuditorAware를 구현해야 하므로, JpaConfig에 내부 static class로 간단히 구현했습니다.
- `PrincipalDetails`에 memberId에 getter 어노테이션을 달아줬는데, 이는 AuditorAware에서 활용하기 위함입니다.
 String으로 반환하는 기존 메서드가 있지만, Long.parse를 하기보다 getter 메서드를 하나 만드는게 좋을 것 같아서 getter 추가했습니다.
- `BaseTimeEntity`에 이제는 시간에 대한 내용만 있지 않으므로, 이름을 `BaseEntity`로 변경했습니다.

## 📝 참고사항
-

## 📚 기타
-

2024-06-26 13:12 UTC, seulgi99 commented
createdBy와 updatedBy의 용도는 무엇인가요?

2024-06-26 13:14 UTC, Sangwook02 commented
> createdBy와 updatedBy의 용도는 무엇인가요?

생성자와 수정자를 트래킹하는 용도입니다~

2024-06-26 13:15 UTC, AlmondBreez3 approved these changes
lgtm
저도 사실 처음에 생성자 보고 constructor인줄알고 착각하고 리뷰달뻔했어용ㅋㅋㅋㅋ

2024-06-26 13:19 UTC, uwoobeat requested changes
`@CreatedBy` 와 `@UpdatedBy` 의 경우 기본적으로 `UserDetails` 의 `getUsername()`을 호출하는 식으로 현재 생성 / 갱신 주체를 지정하고 있고, `PrincipalDetails` 에서 `getUsername()` 이 이미 memberId를 반환하게 만들어줬기 때문에 굳이 `AuditorAware`을 구현하지 않아도 됩니다.

2024-06-26 14:12 UTC, uwoobeat requested changes

2024-06-26 14:15 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/common/model/BaseEntity.java
> +    @Column
위에 다 달려있길래 같이 달아줬었는데 엔티티들처럼 옵션 있는것만 남기고 제거했습니다

2024-06-26 14:19 UTC, uwoobeat requested changes

2024-06-26 14:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/global/config/JpaConfig.java
> +            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
이 로직은 `MemberUtil` 에 있는 것과 중복되는 것 아닌가요?
AuditorAwareImpl을 스프링 빈으로 등록한다면 `MemberUtil` 을 주입받아서 `getCurrentMemberId()` 를 사용할 수 있을 것 같습니다. 그러려면 별도 클래스로 분리해야겠네요

2024-06-27 05:18 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/global/config/JpaConfig.java
> +            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
수정했습니다~

2024-06-28 12:07 UTC, seulgi99 approved these changes
좋습니다! 고생하셨습니다~~

2024-06-28 12:22 UTC, uwoobeat approved these changes
lgtm
그런데 매번 테스트를 할 때마다 createdBy, updatedBy auditing을 위해서 reloginAs를 호출하는 건 별로 안좋은 것 같아요.
시큐리티 컨텍스트에 값이 없으면 null을 반환하게 하거나 하는 식으로 테스트에서 relogin 없이 로직을 작성할 수 있게 하는게 좋을 것 같습니다~

2024-06-28 12:34 UTC, Sangwook02 reviewed
> lgtm 그런데 매번 테스트를 할 때마다 createdBy, updatedBy auditing을 위해서 reloginAs를 호출하는 건 별로 안좋은 것 같아요. 시큐리티 컨텍스트에 값이 없으면 null을 반환하게 하거나 하는 식으로 테스트에서 relogin 없이 로직을 작성할 수 있게 하는게 좋을 것 같습니다~

이 부분이 저도 뭔가 찝찝했는데 AuditorAwareImpl에서 memberUtil 호출하는 부분을 try-catch로 감싸면 test에서 auditing 때문에 넣는 Relogin 로직을 제거할 수 있겠네요.

이것만 수정하고 머지하겠습니다~

2024-06-28 12:49 UTC, merged