feat: 임시 주문 생성 API 구현
GDSC-Hongik/gdsc-server pull request #430
Opened 2024-07-01 13:47 UTC by uwoobeat

## 🌱 관련 이슈
- close #343

## 📌 작업 내용 및 특이사항
### 주문 엔티티 구현
- 결제 플로우의 경우 임시 주문 생성 -> 결제 성공 후 완료 처리하는 방식으로 진행됨
- 일단 주문에 사용되는 연관 엔티티의 ID 정보 및 금액정보만 저장 -> 추후 토스페이먼츠 측에서 전달하는 정보 저장할 예정
- 발급쿠폰의 경우 사용할 수도, 사용하지 않을 수도 있음
- 금액정보의 경우 `MoneyInfo` VO로 관리 -> `주문총액 - 쿠폰할인금액 = 최종결제금액` 불변식 지키기 위함 (테스트 참고)

### 임시 주문 발급 로직 설명
- 요청으로는 1) 주문 nano id 2) 회비납입상태를 갱신하고자 하는 멤버십 id 3) (있는 경우) 사용하려는 발급쿠폰 id 4) 클라이언트에서 사용자에게 디스플레이한 금액 정보를 받는다
- 발급쿠폰 id가 요청 바디에 담겼다면 조회, 아니라면 null
- 관련 엔티티를 조회하고, VO를 생성한 다음, 도메인 서비스에 해당하는 `OrderValidator` 에게 결제 유효성 검증 요청

### 도메인 서비스 `OrderValidator`
- 주문 검증기는 아래와 같은 도메인 규칙을 검증함
    1. 멤버십의 대상 멤버가 현재 로그인한 멤버와 일치하는가?
    2. 멤버십의 정회원 승급조건 중 회비납입상태를 아직 충족하지 못했는가?
    3. 멤버십이 참조하는 리쿠르팅이, 현재 지원 가능한 리쿠르팅인가?
    4. (발급쿠폰이 있다면) 발급쿠폰의 소유자가 현재 로그인한 멤버와 일치하는가?
    5. (발급쿠폰이 있다면) 발급쿠폰이 사용 가능한가? (== 회수되지 않았고, 사용되지 않았는가?)
    6. 주문총액이 현재 멤버십의 리쿠르팅의 회비와 일치하는가?
    7. (발급쿠폰이 없다면) 쿠폰할인금액은 0인가?
    8. (발급쿠폰이 있다면) 쿠폰할인금액은 쿠폰의 할인금액과 일치하는가?
- 멤버가 준회원인지 검증 안하는 이유 -> 멤버십 생성하려면 준회원이어야 하기 때문에 필요없음 

## 📝 참고사항
- `OrderValidator` 는 도메인 서비스에 해당하며, 추후 `@Component` 대신 wrapping된 별도 어노테이션으로 변경할 예정
- 어드민도 멤버십 신청 / 회비 납입이 가능하게 해야 하는가? -> 장기적으로는 멤버십 테이블에 기록되면 활동내역이 증빙되므로, 가능하게 하는 게 좋을 것 같음.
- 검증기의 경우 예외 상황에 대한 테스트를 주로 수행하고, 통합 테스트에서는 임시 주문이 정상 생성되는지만 테스트했음

## 📚 기타
-

2024-07-01 14:30 UTC, Sangwook02 requested changes
확인했습니다!

2024-07-01 14:30 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/order/application/OrderServiceTest.java
> +            var request = new OrderCreateRequest(
여기 var 사용하신 이유가 있나요?

2024-07-01 14:30 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/order/application/OrderServiceTest.java
> +    public static final Money MONEY_5000_WON = Money.from(BigDecimal.valueOf(5000));
안 쓰는 상수도 있는 것 같습니다.

2024-07-01 14:30 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/order/application/OrderService.java
> +
개행 필요없지 않나요?

2024-07-01 14:30 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
Member 도메인에 isAssociate로 바꿀 수 있는 부분 있었던 것 같아요.
이슈 만들어서 리팩토링 하면 좋을 것 같습니다!

2024-07-01 14:35 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/order/application/OrderServiceTest.java
> +            var request = new OrderCreateRequest(
가독성 측면에서 이점이 있습니다.
선언문에서 사용하는 것이기 때문에 어떠한 타입을 가진 변수인지 혼동할 일도 없고요.

2024-07-01 14:35 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/order/application/OrderServiceTest.java
> +    public static final Money MONEY_5000_WON = Money.from(BigDecimal.valueOf(5000));
이어서 작업할 때 자주 쓰이게 될 것 같아서 미리 만들어뒀습니다

2024-07-01 14:36 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/order/application/OrderServiceTest.java
> +            var request = new OrderCreateRequest(
특히나 test니까 가독성 챙기는게 좋겠네요

2024-07-01 14:37 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/order/application/OrderService.java
> +
수정할게요

2024-07-01 14:39 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
네 좋습니다
그리고 멤버가 가지고 있는 인스턴스를 바로 리턴하는 것보다 (ex: `member.getStatus() == XXX`) 의미가 더 잘 드러나게 래핑하는 작업도 필요할 것 같아요 (ex: `member.isXXX`)

getter를 별로 안 좋아하는 편이고 가능하다면 아예 안 쓰고 싶지만...  dto 변환때문에 어쩔 수 없이 쓰게 되는 감이 있네요

2024-07-01 14:43 UTC, Sangwook02 approved these changes
한 가지 질문 사항과 함께 어푸루브 해두겠습니다!

2024-07-01 14:43 UTC, Sangwook02 commented on src/test/java/com/gdschongik/gdsc/domain/order/domain/MoneyInfoTest.java
`Money.from(BigDecimal.valueOf(10000))`과 같은 값들을 상수로 처리하지 않으신 이유가 있나요?

2024-07-03 07:05 UTC, uwoobeat commented on src/test/java/com/gdschongik/gdsc/domain/order/domain/MoneyInfoTest.java
네 맞습니다.

테스트에 존재하는 객체는 크게 테스트하려는 대상(SUT) 과 테스트에 필요한 객체(Collaborator) 로 나뉘는데, 이 경우 `MoneyInfo` 가 SUT에 해당합니다. 테스트에 필요한 객체는 SUT를 테스트하기 위해서 미리 상태를 세팅해줘야 하는데, 이를 테스트 픽스처라고 합니다. 저희는 `IntegrationTest` 단 혹은 클래스 내부의 private method 등으로 이러한 테스트 픽스처를 생성해주고 있습니다 (ex. `createAssociateMember`). 텍스트 픽스처에서 일부 필드의 경우 고정된 값으로 채워줘야 하는 경우가 있고 (ex. `recruitment.name`), 이 경우 상수로 추출하여 사용합니다. 단 이 경우에도 모든 값을 상수로 사용하지 않고 파라미터를 통해 테스트마다 다른 값을 넣을 수 있도록 하여 픽스처 변경으로 인해 리팩토링에 취약해지는 일이 없도록 해야 합니다.

픽스처 뿐만이 아니라 테스트 대상 역시도 다른 테스트와 독립적이어야 합니다. 만약 MoneyInfo를 생성하는 테스트라면 해당 MoneyInfo 생성자에 전달할 인자는 다른 테스트와 독립적이어야 합니다. 즉 상수로 추출되어 다른 테스트에서 공유되어서는 안된다는 이야기인거죠

2024-07-03 12:33 UTC, seulgi99 approved these changes
좋습니다! 코멘트 확인바랍니다!우선 어프로브 할게요!
추가적으로 저희 결제 후에 결제api response로 오는 승인번호, 결제금액 등등을 db에 따로 저장해두는게 좋아서 payment이라는 테이블을 만드는건 어떨까요?그리고 order테이블에 fk 하나 묶어 관리하는게 좋을거같아요!

2024-07-03 12:33 UTC, seulgi99 commented on src/main/java/com/gdschongik/gdsc/domain/order/application/OrderService.java
> +                Money.from(request.discountAmount()),
여기서 Money.from(request.discountAmount()) 이렇게 따로 받는 이유가 있을까요??? 

사실 issuedCoupon안에 할인 금액이 있으니 리퀘스트에 discountAmount가 있을 필욘 없다고 생각해서요!

2024-07-03 12:33 UTC, seulgi99 commented on src/main/java/com/gdschongik/gdsc/domain/order/domain/OrderStatus.java
> +    ;
error상태 (결제 실패)도 필요할것 같습니다!
임시 주문 생성 후 해당 주문실패하면 실패상태로 돌려야하니까요!

2024-07-03 12:41 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/order/application/OrderService.java
> +                Money.from(request.discountAmount()),
클라이언트에서 사용자에게 디스플레이한 정보를 검증하는데 목적이 있습니다
사실 다른 금액도 전부 안받아도 되긴 해요. 회비는 리쿠르팅에 있고 말씀하신대로 할인금액도 쿠폰에 있으니깐요

issuedCoupon은 어떠한 이유로 삭제될 수도 있다고 생각하고, 또 coupon의 금액도 변경될 수 있다고 생각합니다
예전에 쿠폰 수정 API에서 할인금액을 제거해두긴 했지만 추후에 정책이 어떻게 바뀔지 모르는 거니까요
조금 더 나가면 추후 할인정책이 바뀌는 경우 (중복할인) 도 생각하면 issuedCoupon으로 들고있는 것보다 복사해서 가지고 있는게 나을 것 같아요

참조 테이블의 값들이 불변하지 않기 때문에 주문 테이블에서 스냅샷 뜨듯이 저장해둔다 보시면 될 것 같습니다~

2024-07-03 12:42 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/order/domain/OrderStatus.java
> +    ;
추가했어용

2024-07-03 12:43 UTC, uwoobeat commented
> 좋습니다! 코멘트 확인바랍니다!우선 어프로브 할게요! 추가적으로 저희 결제 후에 결제api response로 오는 승인번호, 결제금액 등등을 db에 따로 저장해두는게 좋아서 payment이라는 테이블을 만드는건 어떨까요?그리고 order테이블에 fk 하나 묶어 관리하는게 좋을거같아요!

어차피 OneToOne일 것 같아서 vo로 관리하는게 나을 것 같네요
해당 건은 토스페이먼츠 openfeign 연동하면서 작업해둘게요

2024-07-03 12:45 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/order/application/OrderService.java
> +                Money.from(request.discountAmount()),
그리고 불변 이야기하니까 생각난건데 주문 테이블 필드 (가령 금액정보들) 를 `updatable=false` 걸면 어떨까 싶네요
어떻게 생각하시나요?

2024-07-03 12:51 UTC, merged

2024-07-03 12:53 UTC, seulgi99 commented on src/main/java/com/gdschongik/gdsc/domain/order/application/OrderService.java
> +                Money.from(request.discountAmount()),
updatable=false 걸면 어떨까 싶네요
어떻게 생각하시나요?

-> 이거 좋습니다. 불변해야하니까요