✨ 이메일 인증 기능 구현
GDSC-Hongik/gdsc-server pull request #57
Opened 2024-02-11 19:46 UTC by binary-ho

## 🌱 관련 이슈
#28 

## 📌 작업 내용 및 특이사항
- 12일에 유진님과 얘기해서 gmail password 채워 넣고 조금 더 수정해야 완성이지만, 리뷰를 위해 미리 OPEN합니다
- 네이밍 맘에 안 드는 부분이 많은데 같이 봐주시면 감사하겠습니다.

## 📝 참고사항
-

## 📚 기타
-

2024-02-12 02:29 UTC, uwoobeat requested changes
PR, 커밋 컨벤션 맞춰주세요~

2024-02-12 02:29 UTC, Sangwook02 requested changes
몇가지 제안과 오타 수정사항 등 확인했습니다!

2024-02-12 02:29 UTC, Sangwook02 commented on src/main/resources/application.yml
> +  password: ${GMAIL_PASSWORD}
redis, storage처럼 이메일은 yaml 파일을 분리하지 않는게 일반적인가요?

2024-02-12 02:29 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/integration/HongikUnivEmailValidator.java
> +    private static final String EMAIL_REGEX = "^[^\\W&=_'-+,<>]+(\\.[^\\W&=_'-+,<>]+)*@g\\.hongik\\.ac\\.kr$";
다른 정규표현식을 모두 RegexConstant에서 관리하고 있는데 이 경우에는 RegexConstant에서 관리하지 않는 특별한 이유가 있을까요?

2024-02-12 02:29 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/integration/VerificationMailContentWriter.java
> +        + "CODE : <strong>";
1. "이메일 인증 메일입니다." 대신 "재학생 인증 메일입니다." 어떤가요?

2. '감사힙니다' 오타있습니다!

2024-02-12 02:39 UTC, uwoobeat requested changes
컨트롤러 클래스가 없는 것 같은데 체크 부탁드립니다~

2024-02-12 02:39 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/HongikUnivEmailValidator.java
> +package com.gdschongik.gdsc.domain.integration;
유틸리티로 빼는 게 맞을 것 같습니다~

2024-02-12 02:39 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/JavaMailSender.java
> +    private static final String SENDER_PERSONAL = "GDSC Hongik 운영팀";
`Constant` 클래스로 분리하면 더 좋을 것 같습니다~

2024-02-12 02:39 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/JavaMailSenderConfig.java
> +    private String id;
`MailProperty` 로 분리해서 사용하면 좋을 것 같아요~

2024-02-12 02:39 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/JavaMailSender.java
> +            throw new RuntimeException(e);
커스텀 예외로 변경해주시면 좋을 것 같아요~

2024-02-12 02:39 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/JavaMailSender.java
> +@Service
서비스 계층이라고 보는 것이 맞나? 라는 의문이 드네요.
도메인이랑 상호작용하는 부분이 없으니 유틸리티라고 보는 게 맞지 않을까 싶습니다~

2024-02-12 02:39 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/MailSender.java
> +    void send(String recipient, String content);
메일 전송 성공/실패를 전달받을 수 있는 방법은 존재하지 않나요?

2024-02-12 02:39 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/VerificationMailContentWriter.java
> +    private static final String NOTIFICATION_MESSAGE = "<div style='margin:20px;'>"
인증 코드 입력방식 말고, 인증 URL 클릭하는 방식으로 처리하는게 어떨까 싶습니다~
stoplight 명세 확인해보시면 좋을 것 같아요

2024-02-12 04:05 UTC, binary-ho commented on src/main/resources/application.yml
> +  password: ${GMAIL_PASSWORD}
일반적이라기 보다는 상황에 따라 다를거 같아요 ㅎㅎ 
한번 고민해볼게요 감사합니다!

2024-02-12 04:06 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/integration/HongikUnivEmailValidator.java
> +    private static final String EMAIL_REGEX = "^[^\\W&=_'-+,<>]+(\\.[^\\W&=_'-+,<>]+)*@g\\.hongik\\.ac\\.kr$";
여기서 필요해서 가지고 있었는데, RegexConstant로 옮기겠습니다!

2024-02-12 04:06 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/integration/JavaMailSender.java
> +            throw new RuntimeException(e);
헉 감사합니다!!

2024-02-12 04:07 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/integration/JavaMailSender.java
> +@Service
그게 맞는 것 같아요! 말씀 감사합니다 ㅎㅎ

2024-02-12 04:07 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/integration/MailSender.java
> +    void send(String recipient, String content);
확인해보겠습니다!

2024-02-12 04:07 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/integration/VerificationMailContentWriter.java
> +    private static final String NOTIFICATION_MESSAGE = "<div style='margin:20px;'>"
죄송합니다 확인해보겠습니다!

2024-02-12 04:08 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/integration/VerificationMailContentWriter.java
> +        + "CODE : <strong>";
놓쳐서 죄송합니다!
꼼꼼하게 봐주셔서 감사합니다!

2024-02-13 08:04 UTC, uwoobeat reviewed
PR 본문에 `close #28` 넣어주세요.
++ 커밋 컨벤션 맞춰서 `feat: {commit message}` 와 같이 작성해주세요.

2024-02-13 11:19 UTC, uwoobeat requested changes

2024-02-13 11:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/HongikUnivEmailValidator.java
> +    private static final String HONGIK_UNIV_MAIL_DOMAIN = "@g.hongik.ac.kr";
Constant로 빼는 게 좋을 것 같습니다

2024-02-13 11:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/EmailVerificationCodeRepository.java
> +package com.gdschongik.gdsc.domain.integration;
email 패키지로 이름을 지정하지 않은 이유가 있으신가요?

2024-02-13 11:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/JavaMailSenderConfig.java
> +public class JavaMailSenderConfig {
config 패키지로 관리해줘야 할 것 같습니다.

2024-02-13 11:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/JavaMailSenderConfig.java
> +    private Properties getMailProperties() {
yml 파일에 작성하지 않고 Properties 객체에 하드코딩하신 이유가 궁금합니다~
EmailProperty와 통합이 불가능한가요?

2024-02-13 11:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/JavaMailSender.java
> +            throwCustomExceptionWithAdditionalMessage(ErrorCode.MESSAGING_EXCEPTION, e.getMessage());
바로 new CustomException으로 던져도 되지 않나요?
별도 메서드로 추출하신 이유가 궁금합니다.
```suggestion
            throw new CustomException(ErrorCode.MESSAGING_EXCEPTION, e.getMessage());
```

2024-02-13 11:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/UnivEmailVerificationService.java
> +        mailSender.send(email, "GDSC Hongik 이메일 인증 코드입니다.", mailContent);
의미있는 문자열은 상수로 추출해서 관리하면 좋을 것 같습니다.

2024-02-13 11:19 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/integration/UnivEmailVerificationService.java
> +    public void validateCodeMatch(String email, String userInputCode) {
사용처가 없는 것 같습니다.

2024-02-15 02:41 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/integration/JavaMailSender.java
> +            throwCustomExceptionWithAdditionalMessage(ErrorCode.MESSAGING_EXCEPTION, e.getMessage());
일단 위 try-catch문에선 MessagingException를 잡고 있습니다. 이 MessagingException는 상황에 따라 message를 통해 exception 발생 사유를 간단하게 설명합니다. 

개인적으로 느끼기엔 간단한 설명이 부족하게 느껴져서 MESSAGING_EXCEPTION이 가지고 있는 메시지인 "수신자 이메일이 올바르지 않습니다."와 MessagingException이 건내주는 message를 합치고 싶었습니다.

예를 들어 MessagingException이 전달하는 메시지가 "No From address"인 경우, "수신자 이메일이 올바르지 않습니다. : No From address"와 같은 형태로 합쳐서 건내주고자 했습니다.

이런 상황에선 아래와 같은 코드가 catch문에 들어가게 되었는데요?

```java
String errorMessage = ErrorCode.MESSAGING_EXCEPTION.getMessage() + " : " + e.getMessage();
throw new CustomException(ErrorCode.MESSAGING_EXCEPTION, errorMessage);
```

이 2줄의 코드가 두 군데에서 중복되어 사용되기도 하고,
읽는 사람에게 추가적인 메시지를 더하겠다는 의도를 전달하고 싶어 메서드로 분리하게 되었습니다~

2024-02-15 02:56 UTC, Sangwook02 requested changes
figma 확인 부탁드립니다!

2024-02-15 02:56 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/email/api/UnivEmailVerificationLinkSendController.java
> +    public ResponseEntity<Void> sendUnivEmailVerificationLink() {
figma를 보시면 기획이 조금 바뀌어 있습니다.
현재 로직은 service에서 db에 저장된 email을 가져오는 것으로 보이는데요
api request body로 이메일을 받아야 할 것 같습니다.
figma 확인해보시고 수정해주세요!

2024-02-15 03:38 UTC, Sangwook02 requested changes

2024-02-15 03:38 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationService.java
> +        Member member = getMemberByUnivMail(univEmail);
'인증 메일 보내기' 요청에서 redis에만 저장하고 member의 univEmail 필드는 업데이트를 안 하는 것으로 보입니다.
그럼 이 부분에서 항상 Exception이 발생하지 않나요?
확인부탁드려요~

2024-02-15 04:20 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationService.java
> +        Member member = getMemberByUnivMail(univEmail);
꼼꼼하게 봐주셔서 정말 감사합니다!
명세 잘못 알고 있을 때 짰던 부분이네요,, 전체적으로 다시 살펴보겠습니다!

2024-02-15 10:19 UTC, Sangwook02 requested changes
변수랑 메서드명 suggestion 세 가지랑
로직에 대한 부분 2개 있습니다.

작업양이 많아서 한번에 리뷰를 못 드리네요.. 죄송합니다😢

2024-02-15 10:19 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationService.java
> +        UnivEmailVerification univEmailByVerificationCode = getUnivEmailVerification(verificationCode);
```suggestion
        UnivEmailVerification univEmailVerification = getUnivEmailVerification(verificationCode);
```

2024-02-15 10:19 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/domain/Requirement.java
> +    public void updateUnivState(RequirementStatus univStatus) {
변수명이랑 통일감 있게 가면 좋을 것 같습니다.
```suggestion
    public void updateUnivStatus(RequirementStatus univStatus) {
```

2024-02-16 00:54 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
> +        });
머리 속으로는 그렇게 짠다고 생각했는데, 실제 코드는 저렇게 됐네요..
부끄럽습니다.. 봐주셔서 감사합니다!

꼼꼼히 체크하던, 테스트를 작성하던 해야겠군요
급한 작업들 다 끝나면 테스트 부터 작성해야겠습니다..

2024-02-16 03:24 UTC, uwoobeat reviewed
기능 코멘트에 대략적인 설명좀 부탁드려요.
지금 기능 사이즈가 커서 간단하게 설명 보면서 리뷰하는 게 좋을 것 같습니다.

++ 해당 기능 테스트로 정상작동하는거 체크하셨는지도 궁금합니다

2024-02-16 14:08 UTC, binary-ho commented
> 기능 코멘트에 대략적인 설명좀 부탁드려요. 지금 기능 사이즈가 커서 간단하게 설명 보면서 리뷰하는 게 좋을 것 같습니다.
> 
> ++ 해당 기능 테스트로 정상작동하는거 체크하셨는지도 궁금합니다

@uwoobeat 

애초애 2개로 나누었어야 했는데 아쉬움이 많이 남습니다..

기본적으로 Service 클래스는 2개로 나뉩니다.
1. 재학생 "인증링크"를 전송하는 UnivEmailVerificationLinkSendService
2. 인증 코드를 통해 유저의 재학생 메일을 인증해주는 UnivEmailVerificationService


# 1. UnivEmailVerificationLinkSendService
univEmail을 받아 인증 메일 전송을 수행합니다.
1. 홍익대학교 이메일이 맞는지 검증
2. 해당 이메일로 인증한 이력이 없음을 검증
3. 랜덤 인증 "코드" 발급
4. 인증 "링크" 전송 (인증 링크는 유저가 클릭하게 될 인증 코드가 포함된 링크입니다.)
5. 인증 코드를 메모리 저장소에 저장

```java
public void send(String univEmail) {
    hongikUnivEmailValidator.validate(univEmail);
    validateUnivEmailNotVerified(univEmail);

    String verificationCode = verificationCodeGenerator.generate();
    sendVerificationLink(univEmail, verificationCode);

    saveUnivEmailVerification(univEmail, verificationCode);
}
```

4, 5번 메서드에 대해 추가로 설명하겠습니다.

## 1.1 sendVerificationLink와 MailSender
링크를 생성하고 초대 메일의 문구를 작성합니다.
MailSender를 이용해 메일을 전송합니다. (구현체 JavaMailSender)

```java
private void sendVerificationLink(String univEmail, String verificationCode) {
    String verificationLink = verificationLinkUtil.createLink(verificationCode);
    String mailContent = verificationMailContentWriter.write(verificationLink, VERIFICATION_CODE_TIME_TO_LIVE);

    mailSender.send(univEmail, UnivEmailVerificationConstant.VERIFICATION_EMAIL_SUBJECT, mailContent);
}
```

## 1.2 saveUnivEmailVerification
MemberUtil을 통해 현재 로그인한 유저의 id를 가져옵니다.
인증 코드를 Key로, 인증 코드, 홍익대학교 이메일, 유저 아이디를 Redis에 저장합니다.

인증 코드가 Key인 이유는 나중에 유저가 링크를 눌렀을 때 빠르게 객체를 찾기 위함입니다.
홍익대학교 이메일이 Key인 경우 유저의 중복 발급을 막기 용이하나, 일단은 그런 경우는 일단 배제하기로 했습니다. 인증 코드가 Key일 떄의 이득이 더 있다고 생각했습니다. 필요한 경우 다른 방법으로 막는게 좋아 보입니다.
또한 매우 낮은 확률로 랜덤 인증 코드가 겹치는 경우도 배제했습니다. 추후 1번 정도의 리트라이 로직을 넣는 것도 괜찮을 것 같습니다.

```java
private void saveUnivEmailVerification(String univEmail, String verificationCode) {
    Long currentMemberId = memberUtil.getCurrentMemberId();
    UnivEmailVerification univEmailVerification = new UnivEmailVerification(
            verificationCode, univEmail, currentMemberId, VERIFICATION_CODE_TIME_TO_LIVE.toSeconds());

    univEmailVerificationRepository.save(univEmailVerification);
}
```

이렇게 하면 전송과 발급 과정이 끝나게 됩니다.


# 2. UnivEmailVerificationService
유저가 verificationCode가 포함된 링크를 누르는 경우 인증을 해주는 Service입니다.
redis 저장소에서 verificationCode를 이용해 홍익대학교 이메일과, 유저 id를 가져옵니다. 

이후 유저 id로 유저 객체를 가져옵니다. 이후 유저의 univEmail를 업데이트 해주고, 유저 Requirement의 univStatus 또한 VERIFIED로 업데이트 해줍니다. 

```java
public void verifyMemberUnivEmail(String verificationCode) {
    UnivEmailVerification univEmailVerification = getUnivEmailVerification(verificationCode);
    Member member = getMemberById(univEmailVerification.getMemberId());
    member.completeUnivEmailVerification(univEmailVerification.getUnivEmail());
}
```

<br> <br>

맴버 안의 update 메서드

```java
public class Member extends BaseTimeEntity {

    ...(생략)

    public void completeUnivEmailVerification(String univEmail) {
        this.univEmail = univEmail;
        requirement.updateUnivStatus(RequirementStatus.VERIFIED);
    }

    ....(생략)
}
```


# 3. 추가 설명이 필요한 유틸 클래스들

## 3.1 VerificationCodeGenerator
랜덤 코드의 발급은 간단하게 RandomStringUtils를 통해 생성합니다. 16자의 코드를 생성하고, 아스키 테이블의 '0' 부터 'z' 사이의 문제들로 생성됩니다.

random 메서드의 4, 5 번째 파라미터에 true를 넣어, 특수문자를 모두 제외하고 숫자와 알파벳 대소문자로만 코드를 만들도록 했습니다. 

```java
@Component
public class VerificationCodeGenerator {

    private static final int VERIFICATION_CODE_LENGTH = 16;
    private static final char RANGE_START_CHAR = '0';
    private static final char RANGE_END_CHAR = 'z';

    public String generate() {
        return RandomStringUtils.random(VERIFICATION_CODE_LENGTH, RANGE_START_CHAR, RANGE_END_CHAR, true, true);
    }
}

```

## 3.2 VerificationLinkUtil
EnvironmentUtil을 활용해 환경 상태에 따라 다른 Link를 생성합니다.

```java
  private String getClientUrl() {
      return switch (environmentUtil.getCurrentProfile()) {
          case PROD -> PROD_CLIENT_URL;
          case DEV -> DEV_CLIENT_URL;
          default -> LOCAL_VITE_CLIENT_SECURE_URL;
      };
  }
```

2024-02-16 14:28 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
> +        String verificationCode = verificationCodeGenerator.generate();
redis에 저장해야 하는 문제 때문에 service에서 직접 호출할 수밖에 없는 상황이군요..
확인했습니다!

2024-02-16 14:31 UTC, Sangwook02 approved these changes
service쪽에 하나 더 리뷰 남겼습니다!
미리 approve 해둘게요~
감사합니다👍👍

2024-02-16 14:31 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
> +    }
send에서 또 다른 send를 부르는게 살짝 어색한 것 같아요
mailSender.send를 위에 있는 public send에서 호출하도록 하고 메서드 이름을 writeMailContent 같은 이름으로 바꿔봐도 좋을 것 같습니다!

2024-02-16 17:09 UTC, uwoobeat requested changes

2024-02-16 17:09 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/global/util/Pair.java
> +public record Pair<T>(String key, T value) {}
`Map.Entry` 를 고려해보시기 바랍니다. 패키지도 잘못되어 있는 것 같습니다.

2024-02-16 17:09 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/global/property/email/EmailProperty.java
> +public record EmailProperty(Gmail gmail, String host, int port, String encoding, JavaMailProperty javaMailProperty) {}
프로퍼티 내부 구성요소들은 inner record 클래스로 선언하여 사용 가능합니다. [(참고링크)](src/main/java/com/depromeet/infra/config/oidc/OidcProperties.java)

2024-02-16 17:09 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/global/util/email/HongikUnivEmailValidator.java
> +public class HongikUnivEmailValidator {
email 패키지의 유틸리티와 global 패키지의 email 유틸리티의 분류 기준이 궁금합니다.

2024-02-16 17:09 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/global/config/JavaMailSenderConfig.java
> +    public JavaMailSender javaMailSenderBean() {
빈 네이밍 컨벤션을 지키는 것이 좋아보입니다.

2024-02-17 11:35 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
> +    }
좋습니다 ㅎㅎ

2024-02-17 11:35 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/api/UnivEmailVerificationController.java
> +public class UnivEmailVerificationController {
확인했습니다 ㅎㅎ

2024-02-17 11:36 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
> +        });
find결과가 present일때 (객체가 DB에 있을 때) 예외를 발생생시키는 상황입니다!
orElseThrow는 객체가 없을 때 예외를 던지는 메서드로 알고 있는데 확인해주실 수 있을까요??

2024-02-17 11:42 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationService.java
> +@Transactional
확인했습니다 감사합니다!

2024-02-17 11:43 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
> +    UNIV_EMAIL_ALREADY_VERIFIED(HttpStatus.CONFLICT, "이미 가입된 Univ Email 입니다."),
확인했습니다 감사합니다!

2024-02-17 11:58 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
> +        String mailContent = verificationMailContentWriter.write(verificationLink, VERIFICATION_CODE_TIME_TO_LIVE);
생각해 봤는데, 과한 분리가 맞는 것 같습니다! 
이 객체 안에서 처리해보겠습니다 짚어주셔서 감사합니다 ㅎㅎ

2024-02-17 11:59 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
> +    private void sendVerificationLink(String univEmail, String verificationCode) {
확인했습니다!

2024-02-17 12:18 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/global/util/email/HongikUnivEmailValidator.java
> +public class HongikUnivEmailValidator {
정말 "재학생 인증 메일"과 무관한 email에 관한 요소들을 globals에, "재학생 인증 메일과"유관한 요소들을 domain email 패키지에 두었습니다.

"재학생 인증 메일"이라는 context에 종속된 요소들이라도, global에 있는게 좋다고 생각하실까요??

2024-02-17 12:18 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/global/property/email/EmailProperty.java
> +public record EmailProperty(Gmail gmail, String host, int port, String encoding, JavaMailProperty javaMailProperty) {}
확인했습니다!

2024-02-17 12:44 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/api/UnivEmailVerificationController.java
> +public class UnivEmailVerificationController {
엔드포인트와 사용 Service가 다르기 떄문에 분리해 보았습니다. 
패키지로 구분이 가능하다고 생각했었는데, 읽는 분 입장에서 불필요하게 느껴진시다면 말씀 주세요 ㅎㅎ

2024-02-17 12:46 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationService.java
> +@Transactional
확인했습니다

2024-02-17 13:06 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/global/config/JavaMailSenderConfig.java
> +    public JavaMailSender javaMailSenderBean() {
확인했습니다!

2024-02-17 13:14 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/global/util/Pair.java
> +public record Pair<T>(String key, T value) {}
Map의 Entry는 정말 Map의 내부에서 사용될 Entry로써 사용될 떄 사용하는 것이 옳다고 생각해서 직접 정의해 보았습니다! 결국 사용방법은 동일하지만, 그 의미가 다르다고 생각되서 사용을 꺼렸습니다.

혹시 Map.Entry 사용 고려를 권하신 이유를 들려주실 수 있을까요?

2024-02-17 13:15 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/global/util/Pair.java
> +public record Pair<T>(String key, T value) {}
패키지는 어디에 두는 것이 좋을까요?

2024-02-18 16:16 UTC, uwoobeat requested changes

2024-02-18 16:16 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationService.java
> +@Transactional
readOnly = true를 클래스 레벨에서 선언할 것인가 메서드 레벨에서 선언할 것인가에 대한 이야기로 이해하면 될까요?

1. 
결국 메서드 레벨에서 `@Transactional(readOnly = true)` 다는 것을 실수하는 경우와 `@Transactional` 다는 것을 실수하는 경우에 대한 문제인 것 같습니다. 전자를 실수하면 조회 성능이 나빠지고 후자를 실수하면 쓰기 지연이 발생하지 않겠네요.

후자의 경우 테스트로 검증이 가능하지만 전자의 경우 검증이 불가능하다는 점에서 클래스 레벨에서는 `@Transactional(readOnly = true)` 을 달아주고 쓰기 (CUD) 작업인 경우 `@Transaction` 을 달아주는 방식을 사용하게 되는 것 같습니다.

2.
그리고 메서드가 하나인 클래스라 하더라도 이러한 컨벤셔널한 부분은 통일되어야 한다고 생각합니다. 
만약 우리가 `readOnly` 클래스 레벨에 달아주기로 해놓고 여기서만 그렇게 하지 않는다면,
추후 먼 미래 해당 클래스에 메서드가 추가되는 경우 기존 컨벤션에 적응되 작업자가 실수할 수도 있습니다.

2024-02-18 16:16 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/email/constant/UnivEmailVerificationConstant.java
> +
상수 클래스 멤버 개행 관련해서 스타일 컨벤션 한번만 체크해주세요.

2024-02-18 16:16 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/global/util/Pair.java
> +public record Pair<T>(String key, T value) {}
Map.Entry의 사용의미에 대해서 잘못 알고 계신 것 같습니다. 해당 클래스는 key-value 단일 쌍을 위해서도 사용될 수 있습니다.

굳이 자료구조를 새로 만들어서 관리 포인트를 늘릴 필요가 없습니다.

2024-02-18 16:16 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/global/util/email/HongikUnivEmailValidator.java
> +public class HongikUnivEmailValidator {
일관된 분류기준만 있다면 무엇이든 상관없습니다.

그리고 `HongikUnivEmailValidator`는 "재학생 인증 메일" 의 컨텍스트와 무관하다고 생각하시는지, 그렇다면 왜 그렇게 생각하셨는지 궁금합니다.

2024-02-19 10:34 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/api/UnivEmailVerificationController.java
> +public class UnivEmailVerificationController {
좋은 글 감사합니다! 공감되는 내용이네요 ㅎㅎ
1. 메일 발송은 `/onboarding/send-verification-email`을 사용하고, 메일 인증은 `onboarding/verify-email`을 사용하는데, 같은 엔드포인트로 보는게 맞을까요?
2. 좋은 말씀입니다! 이 PR Merge이후에 시간이 되는 대로 고쳐볼게요

2024-02-19 10:38 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/global/util/Pair.java
> +public record Pair<T>(String key, T value) {}
혹시 말씀주신 의미로 사용해도 좋다는 관련 자료가 있을까요??

2024-02-19 10:40 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/global/util/email/HongikUnivEmailValidator.java
> +public class HongikUnivEmailValidator {
HongikUnivEmailValidator는 잘못 놓았네요..
이메일과 관련된 util 객체들은 global로 옮겨두겠습니다!

2024-02-19 10:41 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
> +        UnivEmailVerification univEmailVerification = new UnivEmailVerification(
확인했습니다!

2024-02-19 10:41 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/constant/UnivEmailVerificationConstant.java
> +
확인했습니다!

2024-02-19 13:04 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/global/util/Pair.java
> +public record Pair<T>(String key, T value) {}
### 요약
- key-value single pair에 대해 `AbstractMap.SimpleEntry` 를 사용할 것을 제안하는 여러 레퍼런스가 있습니다.
- Map 내부의 Entry를 사용하기 싫다면 Apache Commons Lang 의존성을 추가해서 Pair 클래스를 사용하면 됩니다.
- 외부 의존성을 추가하기 싫다면 그냥 Map.Entry 구현체를 쓰면 됩니다.
- Pair 클래스는 객체지향적으로 좋지 않을 수도 있습니다.

### 본문

https://www.baeldung.com/java-pairs

먼저 질문에 대한 답부터 드리자면... 
위 글에는 자바에서 key-value 쌍을 처리하기 위해서 `AbstractMap.SimpleEntry` 를 사용할 수 있다는 것을 소개하고 있습니다. 

https://stackoverflow.com/questions/3110547/java-how-to-create-new-entry-key-value
https://stackoverflow.com/questions/2973041/a-keyvaluepair-in-java

그리고 위의 2개의 스택오버플로우 글은 진호님과 같은 생각을 한 사람들을 위한 글입니다.
2번째 레퍼런스의 댓글을 보시면 어느정도 답을 얻을 수 있습니다.

> I prefer commons Pair personally - doesn't seem right to have to dig for a class inside of AbstractMap. But if you don't want to depend on commons lang for some reason, I could see that.
>
> 개인적으로는 Commons Pair를 선호합니다 - AbstractMap 내부에서 클래스를 찾아야 한다는 것이 올바르지 않은 것 같습니다. 하지만 어떤 이유로든 Commons Lang에 의존하고 싶지 않다면, 그것도 이해할 수 있습니다.

Pair을 사용하고 싶다면 `org.apache.commons.lang3.tuple` 패키지의 `pair` 을 사용하면 됩니다. 어느 쪽이든 직접 구현하는 편보다는 낫습니다. 유지보수 포인트를 늘리는 것보다는 외부 의존성을 늘리는 것이 낫다고 생각합니다. 그리고 외부 의존성을 늘리는 편보다는 자바의 기본 패키지 (`java.util`) 의 `Map.Entry` 를 사용하는 편이 낫습니다.

그리고 Pair의 사용이 객체지향적으로 좋지 않다는 레퍼런스가 있습니다.
하지만 최근 라이브러리들은 Pair 구현체를 제공하는 편이긴 합니다. 심지어 안드로이드도 자체적으로 Pair 클래스를 제공합니다.
옛날 글이라는 점은 감안해주세요.

Google Guava에서는 Pair 도입이 그닥 좋지 않다고 이야기했습니다.
https://groups.google.com/g/guava-discuss/c/GF4QyBu0gsI

직접 정의한 Pair 클래스의 단점을 제네릭 관점에서 접근한 글입니다.
https://james-iry.blogspot.com/2010/05/anatomy-of-annoyance.html

2024-02-19 13:12 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/email/api/UnivEmailVerificationController.java
> +public class UnivEmailVerificationController {
네 맞습니다. 하나의 컨트롤러로 통일하는 게 맞습니다.

이름은 조금 더 고민해보셔요. 제가 `EmailController` 로 합치는 게 좋다고 했지만 사실은 `OnboardingXXXController` / `AdminXXXController` 와 같이 분리해서 사용하고 있습니다. (나중에 온보딩 / 어드민 도메인 분리해두는 것을 염두에 두고 이렇게 작업하고 있습니다)

컨벤셔널하게 간다면 `OnboardingEmailController` 가 맞습니다. 하지만 `EmailController` 가 그렇게 틀렸냐 하면 그건 아닙니다. 예측가능성 vs 유지보수 포인트 줄이기 + 이메일 도메인의 특수성 고려 간 trade-off 잘 고려하셔서 진호님이 자율적으로 선택하시면 될 것 같아요. 언제까지나 제 생각입니다. 이런 문제에 정답은 없으니까요~

2024-02-19 13:16 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
> +        });
제가 잘못 적었네요. `() -> new CustomException(...)` 과 같이 작성하면 어떨까 싶었습니다. 람다 파라미터를 사용하지는 않으니까요~

2024-02-20 10:25 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/api/UnivEmailVerificationController.java
> +public class UnivEmailVerificationController {
조금 헷갈려서 다시 질문드립니다. 현재 메일 발송은 엔드포인트를 /onboarding/send-verification-email을 사용하고, 메일 인증은 엔드포인트로 /onboarding/verify-email 하는데 하나의 엔드포인트로 보신다는 말씀이실까요? 

그래서 최상단에는 @RequestMapping("/onboarding") 이렇게 두고 두개의 메서드에 @PostMapping("send-verification-email"), @GetMapping("verify-email") 이렇게 쓰자고 말씀하신건가요?

아니면 "onboarding/verify-email"과 같은 하나의 엔드포인트로 통일하고 하나에 컨트롤러에 넣어 달라는 말씀이실까요?

2024-02-20 10:26 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
> +        });
위 메서드 ifPresent는 Consumer가 요구되는 메서드로 보여주신 모습과 같이 작성하긴 어렵습니다.
그것과 별개로 ifPresent를 안 쓰는 쪽으로 바꿔보겠습니다.

2024-02-20 11:17 UTC, binary-ho commented on src/main/java/com/gdschongik/gdsc/global/util/Pair.java
> +public record Pair<T>(String key, T value) {}
오! 첫번째 래퍼런스는 저도 이번에 구현하는 과정에서 봤던건데 반갑네요.
1. 저 글에서는 Map의 Entry를 사용하는 법만 알려주고 맥락적으로 왜 사용해도 되는지 이유를 알려주지는 않는 것 같아요.. 아니면 같은 글에 등장하는 대안 5번과 같은 사용은 어떨까요? 지금의 Pair를 PropertyPair로 이름을 바꿔서 사용해 보는 것은 어떻게 생각하시나요?
2. 사실 현재 Property를 위한 용도의 필드 2개인 record인 Pair가 유지보수 포인트를 많이 늘리는 지는 조금 와닿지 않는 것 같습니다... Wrapper Class에 가까운 record class 하나가 추가 되는 상황보다는 외부 의존성을 늘리는 것이 낫다고 생각하시는 부분은 이유를 여쭈어 봐도 될까요? js의 유명한 util용 라이브러리 lodash의 퇴출은 예전 부터 논쟁거리였습니다 [You-Dont-Need-Lodash-Underscore](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore) 퇴출을 원하는 사람들은 대부분 작은 기능을 위해 라이브러리를 사용하면서 여러 문제를 마주하지 말고, 기본적인 언어의 기능을 활용하자는 것이 의견입니다.
3. 그렇다고 Apache Commons Lang의 Pair 클래스를 쓰기 꺼리는 것은 아닙니다. **이걸 사용해볼까요?**
4. 또한 Pair가 객체지향적으로 좋지 않다는 점은 매우 동의합니다.
5. 최하단의 글과 저희의 케이스는 조금 다른 것 같습니다.. 활용처가 매우 다양하고 범용적인 Pair를 정의하면서 생긴 다양한 문제로 느껴집니다. 저희의 경우에는 Property 값을 ConfigurationProperties을 통해 가져올 때만 사용하고 있습니다. 물론 제가 이름을 그렇게 짓지 않았습니다.. **차라리 그런 의미를 가진 PropetyPair로 이름을 바꾸고 사용함은 어떨 것 같나요??**

2024-02-20 12:53 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/email/api/UnivEmailVerificationController.java
> +public class UnivEmailVerificationController {
컨벤션 상으로는 컨트롤러를 `AdminXXXController`, `OnboardingXXXController` 와 같이 분리해서 사용하고 있습니다.

하지만 현재는 어드민에서 이메일 보내는 기능이 존재하지 않고, 
해당 기능이 추가될 가능성이 그리 높다고 보기도 어려우므로, 
`AdminEmailController`, `OnboardingEmailController` 로 분리해야만 하는 것은 아닙니다.
`EmailController` 와 같이 사용할 수도 있습니다.

즉 `컨벤셔널하게` vs `관리포인트를 작게` 중 어느 것을 선택하냐에 대한 문제라는 것입니다.

`OnboardingEmailController` 를 사용한다면 클래스 레벨의 `@RequestMapping("/onboarding")` 이 있어야겠죠.
`EmailController` 를 사용한다면 클래스 레벨의 `@RequestMapping("/onboarding")`  을 사용하든 그냥 해당 어노테이션 없이 가든 자유롭게 선택 가능하겠죠.

결론은 컨트롤러 네이밍을 어떻게 가져가냐에 따라 질문주신 내용에 대한 방향성이 달라진다는 것입니다.

2024-02-24 10:56 UTC, uwoobeat approved these changes
lgtm

2024-02-25 13:43 UTC, merged