refactor: 전화번호를 Embedded로 관리
GDSC-Hongik/gdsc-server pull request #74
Opened 2024-02-15 04:08 UTC by Sangwook02

## 🌱 관련 이슈
- close #73 

## 📌 작업 내용 및 특이사항
- 전화번호를 별도의 클래스로 만들어 관리하고, 해당 클래스에서 hyphen을 넣고 빼는 작업을 처리하도록 했습니다.
- 이로써, 이전에 재현님께서 지적해주신 case (`010-abcd-efgh`에서 `cde`만으로 조회해도 가능해야 한다)를 처리할 수 있게 되었습니다.

## 📝 참고사항
-

## 📚 기타
-

2024-02-15 04:47 UTC, uwoobeat requested changes
현재는 도메인 단에서 전화번호 객체를 관리할 정도의 요구사항이 없다고 생각합니다.
common 패키지에 Phone 공용 DTO 만들어서 entiy - dto 매핑 같은 느낌으로만 사용해도 충분할 것 같아요. 포맷이 걸려있는 다른 필드도 그렇고요

학번은 VO로 관리를 해도 좋다고 생각해요. 학번 / 학과 / 식별자 규칙이 해당 학번에 전부 들어가 있어서, 나중에 관련 정보를 추출해낼 때 (가령 학과 식별이 필요할 때) 비즈니스 로직으로 사용할 가능성이 꽤 크다고 보거든요. 그마저도 당장 급하지는 않고요

다만 전화번호는 별다른 로직이랄 게 없기도 하고 앞으로도 활용 가능성이 적다 생각해서 그냥 공용 DTO 수준으로 다루고 도메인 단에서는 String으로 처리하는 게 맞을 것 같습니다

2024-02-15 05:21 UTC, Sangwook02 commented
> 현재는 도메인 단에서 전화번호 객체를 관리할 정도의 요구사항이 없다고 생각합니다. common 패키지에 Phone 공용 DTO 만들어서 entiy - dto 매핑 같은 느낌으로만 사용해도 충분할 것 같아요. 포맷이 걸려있는 다른 필드도 그렇고요
> 
> 학번은 VO로 관리를 해도 좋다고 생각해요. 학번 / 학과 / 식별자 규칙이 해당 학번에 전부 들어가 있어서, 나중에 관련 정보를 추출해낼 때 (가령 학과 식별이 필요할 때) 비즈니스 로직으로 사용할 가능성이 꽤 크다고 보거든요. 그마저도 당장 급하지는 않고요
> 
> 다만 전화번호는 별다른 로직이랄 게 없기도 하고 앞으로도 활용 가능성이 적다 생각해서 그냥 공용 DTO 수준으로 다루고 도메인 단에서는 String으로 처리하는 게 맞을 것 같습니다

지난번에 말씀하신걸 제가 잘못 이해했나보네요.
common dto 방식으로 수정해보겠습니다

2024-02-17 09:50 UTC, Sangwook02 reviewed
저장 시에는 member가 직접 hyphen 제거, 
response에 전화번호가 필요한 경우에는 dto가 알아서 formatting 하도록 수정했습니다.
나중에 여유가 있으면 dto에서 중복되는 부분들 개선할 수 있도록 해보겠습니다.

2024-02-18 16:20 UTC, uwoobeat requested changes
DB에는 하이픈 없이 저장되어야 합니다.

2024-02-20 05:09 UTC, Sangwook02 commented
> DB에는 하이픈 없이 저장되어야 합니다.

replaceAll("-", "");로 하이픈을 제거하고 저장하도록 구현되어 있습니다.
한번 더 확인해주실 수 있을까요?

2024-02-20 08:30 UTC, uwoobeat requested changes
요청 DTO에서 하이픈 제거된 값으로 받으면 될 것 같습니다. 응답 내려줄 때만 하이픈 넣는 로직 추가해주고요

2024-02-20 13:16 UTC, uwoobeat requested changes
lgtm

2024-02-20 13:17 UTC, merged