feat: 회비 미납 회원 목록 조회 api 구현
GDSC-Hongik/gdsc-server pull request #89
Opened 2024-02-19 06:39 UTC by Sangwook02

## 🌱 관련 이슈
- close #78

## 📌 작업 내용 및 특이사항
- 회비 미납 회원 조회 api를 구현했습니다.
- 기존에 RepositoryImpl에서 사용하던 `paymentVerified`메서드를 `eqPaymentStatus`로 수정하여 재활용 가능하도록 했습니다.

## 📝 참고사항
-

## 📚 기타
-

2024-02-19 06:43 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
> +    @GetMapping("/unpaid")
더 적절한 path가 생각나시는 분 계시면 추천 부탁드려요~

2024-02-19 13:59 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
> +    @GetMapping("/unpaid")
오 좋은 것 같아요
저도 뭔가 unpaid라는 워딩이 뜬금없는 것 같아서 남긴 코멘트였는데 딱 어울리는 것 같네요

2024-02-19 14:08 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
> +    @GetMapping("/unpaid")
기존꺼 수정작업은 리팩토링 이슈로 넣고 새로 작업되는 부분만 반영해주시면 될듯요

2024-02-19 16:11 UTC, uwoobeat requested changes

2024-02-19 16:11 UTC, uwoobeat commented on src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
> +    private BooleanExpression eqRequirementStatus(String requirement, RequirementStatus requirementStatus) {
제네릭으로 처리할 수 있도록 개선해보면 좋을 것 같습니다.
이렇게 하면 매번 requiremen 타입을 사용하는 컬럼이 추가될 때마다 해당 메서드를 변경해줘야 합니다.

2024-02-20 03:49 UTC, Sangwook02 commented on src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
> +    private BooleanExpression eqRequirementStatus(String requirement, RequirementStatus requirementStatus) {
requirement의 변경에 유연하게 대응 가능하도록 수정했습니다

2024-02-20 08:32 UTC, uwoobeat approved these changes
ㅇㅍㅍ

2024-02-20 08:34 UTC, merged