chore : [CI] Pull Request Open, Sync, Closed시 Gradle Build를 수행하는 Workflows 작성
GDSC-Hongik/gdsc-server pull request #9
Opened 2024-01-14 10:02 UTC by binary-ho

## 🌱 관련 이슈
- #8 
- 테스트를 강제하기 위한 PR Code Build

## 📌 작업 내용 및 특이사항
-  Pull Request Open, Synchronize, Closed시 Gradle Build 하는 workflows 작성
- JDK는 CI/CD와 같이 17 버전 temurin 사용 예정 -> [참고글](https://whichjdk.com/ko/)
- Closed시엔 필요 없을 수도 있는데, 혹시 몰라서 넣었음.

2024-01-15 03:14 UTC, Sangwook02 reviewed
확인했습니다!

2024-01-15 03:14 UTC, Sangwook02 commented on .github/workflows/pull_request_gradle_build.yml
> +    types: [opened, synchronize, closed]
closed는 혹시 몰라서 넣으셨다고 적어주셨던데, develop 브랜치 워크플로우에서 push 하면 작동하도록  되어있어서 없어도 되지 않을까 합니다!

이외에 closed로 작동하는 경우가 있을까요?

2024-01-15 05:01 UTC, uwoobeat requested changes

2024-01-15 05:01 UTC, uwoobeat commented on .github/workflows/pull_request_gradle_build.yml
> +          ./gradlew build --no-build-cache
build task 대신 check task 사용하는 편이 좋을 것 같습니다~

2024-01-23 01:36 UTC, uwoobeat requested changes

2024-01-23 01:36 UTC, uwoobeat commented on .github/workflows/pull_request_gradle_build.yml
> +permissions: read-all
디폴트 퍼미션 사용하면 됩니다

2024-01-23 01:36 UTC, uwoobeat commented on .github/workflows/pull_request_gradle_build.yml
> +name : Pull Request Gradle Build 테스트
`Check Style and Test to Develop` 으로 통일하면 좋을 것 같습니다.
실질적으로는 develop 브랜치가 아니라 pr 브랜치지만... 의미만 통하면 되니까요

2024-01-23 01:36 UTC, uwoobeat commented on .github/workflows/pull_request_gradle_build.yml
> +          cache: 'gradle'
gradle build action에서 캐시 사용하고 있으므로 별도로 세팅하지 않아도 됩니다

2024-01-23 08:22 UTC, uwoobeat approved these changes
lgtm

수정 후 머지하시면 됩니다

2024-01-23 08:22 UTC, uwoobeat commented on .github/workflows/pull_request_gradle_build.yml
> +    permissions:
따로 퍼미션 설정하지 않아도, 레포지터리 기본 퍼미션을 따르기 때문에 별도로 설정할 필요가 없다는 의미였습니다~

2024-01-23 11:29 UTC, Sangwook02 commented on .github/workflows/pull_request_gradle_build.yml
> +    permissions:
위에 있는 퍼미션만 보고 밑에 있는 퍼미션을 못 봤네요.
마저 수정했습니다!

2024-01-23 11:30 UTC, Sangwook02 approved these changes
lgtm

2024-01-23 11:31 UTC, merged